// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/MarketEvents.proto

package dalalstreet.socketapi.datastreams;

public final class MarketEvents {
  private MarketEvents() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MarketEventUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.datastreams.MarketEventUpdate)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
     */
    boolean hasMarketEvent();
    /**
     * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
     */
    dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent getMarketEvent();
  }
  /**
   * Protobuf type {@code dalalstreet.socketapi.datastreams.MarketEventUpdate}
   */
  public  static final class MarketEventUpdate extends
      com.google.protobuf.GeneratedMessageLite<
          MarketEventUpdate, MarketEventUpdate.Builder> implements
      // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.datastreams.MarketEventUpdate)
      MarketEventUpdateOrBuilder {
    private MarketEventUpdate() {
    }
    public static final int MARKET_EVENT_FIELD_NUMBER = 1;
    private dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent marketEvent_;
    /**
     * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
     */
    public boolean hasMarketEvent() {
      return marketEvent_ != null;
    }
    /**
     * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
     */
    public dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent getMarketEvent() {
      return marketEvent_ == null ? dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent.getDefaultInstance() : marketEvent_;
    }
    /**
     * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
     */
    private void setMarketEvent(dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent value) {
      if (value == null) {
        throw new NullPointerException();
      }
      marketEvent_ = value;
      
      }
    /**
     * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
     */
    private void setMarketEvent(
        dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent.Builder builderForValue) {
      marketEvent_ = builderForValue.build();
      
    }
    /**
     * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
     */
    private void mergeMarketEvent(dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent value) {
      if (marketEvent_ != null &&
          marketEvent_ != dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent.getDefaultInstance()) {
        marketEvent_ =
          dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent.newBuilder(marketEvent_).mergeFrom(value).buildPartial();
      } else {
        marketEvent_ = value;
      }
      
    }
    /**
     * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
     */
    private void clearMarketEvent() {  marketEvent_ = null;
      
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (marketEvent_ != null) {
        output.writeMessage(1, getMarketEvent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (marketEvent_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMarketEvent());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code dalalstreet.socketapi.datastreams.MarketEventUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate, Builder> implements
        // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.datastreams.MarketEventUpdate)
        dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdateOrBuilder {
      // Construct using dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
       */
      public boolean hasMarketEvent() {
        return instance.hasMarketEvent();
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
       */
      public dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent getMarketEvent() {
        return instance.getMarketEvent();
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
       */
      public Builder setMarketEvent(dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent value) {
        copyOnWrite();
        instance.setMarketEvent(value);
        return this;
        }
      /**
       * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
       */
      public Builder setMarketEvent(
          dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent.Builder builderForValue) {
        copyOnWrite();
        instance.setMarketEvent(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
       */
      public Builder mergeMarketEvent(dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent value) {
        copyOnWrite();
        instance.mergeMarketEvent(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.MarketEvent market_event = 1;</code>
       */
      public Builder clearMarketEvent() {  copyOnWrite();
        instance.clearMarketEvent();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.datastreams.MarketEventUpdate)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate other = (dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate) arg1;
          marketEvent_ = visitor.visitMessage(marketEvent_, other.marketEvent_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent.Builder subBuilder = null;
                  if (marketEvent_ != null) {
                    subBuilder = marketEvent_.toBuilder();
                  }
                  marketEvent_ = input.readMessage(dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(marketEvent_);
                    marketEvent_ = subBuilder.buildPartial();
                  }

                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.datastreams.MarketEventUpdate)
    private static final dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MarketEventUpdate();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static dalalstreet.socketapi.datastreams.MarketEvents.MarketEventUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MarketEventUpdate> PARSER;

    public static com.google.protobuf.Parser<MarketEventUpdate> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
