// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetCompanyProfile.proto

package dalalstreet.socketapi.actions;

public final class GetCompanyProfile {
  private GetCompanyProfile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GetCompanyProfileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetCompanyProfileRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 stock_id = 1;</code>
     */
    int getStockId();
  }
  /**
   * Protobuf type {@code dalalstreet.socketapi.actions.GetCompanyProfileRequest}
   */
  public  static final class GetCompanyProfileRequest extends
      com.google.protobuf.GeneratedMessageLite<
          GetCompanyProfileRequest, GetCompanyProfileRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetCompanyProfileRequest)
      GetCompanyProfileRequestOrBuilder {
    private GetCompanyProfileRequest() {
    }
    public static final int STOCK_ID_FIELD_NUMBER = 1;
    private int stockId_;
    /**
     * <code>optional uint32 stock_id = 1;</code>
     */
    public int getStockId() {
      return stockId_;
    }
    /**
     * <code>optional uint32 stock_id = 1;</code>
     */
    private void setStockId(int value) {
      
      stockId_ = value;
    }
    /**
     * <code>optional uint32 stock_id = 1;</code>
     */
    private void clearStockId() {
      
      stockId_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stockId_ != 0) {
        output.writeUInt32(1, stockId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (stockId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, stockId_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.GetCompanyProfileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetCompanyProfileRequest)
        dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequestOrBuilder {
      // Construct using dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional uint32 stock_id = 1;</code>
       */
      public int getStockId() {
        return instance.getStockId();
      }
      /**
       * <code>optional uint32 stock_id = 1;</code>
       */
      public Builder setStockId(int value) {
        copyOnWrite();
        instance.setStockId(value);
        return this;
      }
      /**
       * <code>optional uint32 stock_id = 1;</code>
       */
      public Builder clearStockId() {
        copyOnWrite();
        instance.clearStockId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetCompanyProfileRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest other = (dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest) arg1;
          stockId_ = visitor.visitInt(stockId_ != 0, stockId_,
              other.stockId_ != 0, other.stockId_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  stockId_ = input.readUInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetCompanyProfileRequest)
    private static final dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetCompanyProfileRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetCompanyProfileRequest> PARSER;

    public static com.google.protobuf.Parser<GetCompanyProfileRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetCompanyProfileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetCompanyProfileResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse result = 1;</code>
     */
    dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse getResult();

    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError();

    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError();

    public dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.ResponseCase getResponseCase();
  }
  /**
   * Protobuf type {@code dalalstreet.socketapi.actions.GetCompanyProfileResponse}
   */
  public  static final class GetCompanyProfileResponse extends
      com.google.protobuf.GeneratedMessageLite<
          GetCompanyProfileResponse, GetCompanyProfileResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetCompanyProfileResponse)
      GetCompanyProfileResponseOrBuilder {
    private GetCompanyProfileResponse() {
    }
    public interface GetCompanyProfileSuccessResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
       */
      boolean hasStockDetails();
      /**
       * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
       */
      dalalstreet.socketapi.models.StockOuterClass.Stock getStockDetails();

      /**
       * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
       */
      int getStockHistoryMapCount();
      /**
       * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
       */
      boolean containsStockHistoryMap(
          java.lang.String key);
      /**
       * Use {@link #getStockHistoryMapMap()} instead.
       */
      @java.lang.Deprecated
      java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory>
      getStockHistoryMap();
      /**
       * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
       */
      java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory>
      getStockHistoryMapMap();
      /**
       * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
       */

      dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory getStockHistoryMapOrDefault(
          java.lang.String key,
          dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory defaultValue);
      /**
       * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
       */

      dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory getStockHistoryMapOrThrow(
          java.lang.String key);
    }
    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse}
     */
    public  static final class GetCompanyProfileSuccessResponse extends
        com.google.protobuf.GeneratedMessageLite<
            GetCompanyProfileSuccessResponse, GetCompanyProfileSuccessResponse.Builder> implements
        // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse)
        GetCompanyProfileSuccessResponseOrBuilder {
      private GetCompanyProfileSuccessResponse() {
      }
      private int bitField0_;
      public static final int STOCK_DETAILS_FIELD_NUMBER = 1;
      private dalalstreet.socketapi.models.StockOuterClass.Stock stockDetails_;
      /**
       * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
       */
      public boolean hasStockDetails() {
        return stockDetails_ != null;
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
       */
      public dalalstreet.socketapi.models.StockOuterClass.Stock getStockDetails() {
        return stockDetails_ == null ? dalalstreet.socketapi.models.StockOuterClass.Stock.getDefaultInstance() : stockDetails_;
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
       */
      private void setStockDetails(dalalstreet.socketapi.models.StockOuterClass.Stock value) {
        if (value == null) {
          throw new NullPointerException();
        }
        stockDetails_ = value;
        
        }
      /**
       * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
       */
      private void setStockDetails(
          dalalstreet.socketapi.models.StockOuterClass.Stock.Builder builderForValue) {
        stockDetails_ = builderForValue.build();
        
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
       */
      private void mergeStockDetails(dalalstreet.socketapi.models.StockOuterClass.Stock value) {
        if (stockDetails_ != null &&
            stockDetails_ != dalalstreet.socketapi.models.StockOuterClass.Stock.getDefaultInstance()) {
          stockDetails_ =
            dalalstreet.socketapi.models.StockOuterClass.Stock.newBuilder(stockDetails_).mergeFrom(value).buildPartial();
        } else {
          stockDetails_ = value;
        }
        
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
       */
      private void clearStockDetails() {  stockDetails_ = null;
        
      }

      public static final int STOCK_HISTORY_MAP_FIELD_NUMBER = 2;
      private static final class StockHistoryMapDefaultEntryHolder {
        static final com.google.protobuf.MapEntryLite<
            java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> defaultEntry =
                com.google.protobuf.MapEntryLite
                .<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory>newDefaultInstance(
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "",
                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                    dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory.getDefaultInstance());
      }
      private com.google.protobuf.MapFieldLite<
          java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> stockHistoryMap_ =
              com.google.protobuf.MapFieldLite.emptyMapField();
      private com.google.protobuf.MapFieldLite<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory>
      internalGetStockHistoryMap() {
        return stockHistoryMap_;
      }
      private com.google.protobuf.MapFieldLite<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory>
      internalGetMutableStockHistoryMap() {
        if (!stockHistoryMap_.isMutable()) {
          stockHistoryMap_ = stockHistoryMap_.mutableCopy();
        }
        return stockHistoryMap_;
      }

      public int getStockHistoryMapCount() {
        return internalGetStockHistoryMap().size();
      }
      /**
       * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
       */

      public boolean containsStockHistoryMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetStockHistoryMap().containsKey(key);
      }
      /**
       * Use {@link #getStockHistoryMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> getStockHistoryMap() {
        return getStockHistoryMapMap();
      }
      /**
       * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
       */

      public java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> getStockHistoryMapMap() {
        return java.util.Collections.unmodifiableMap(
            internalGetStockHistoryMap());
      }
      /**
       * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
       */

      public dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory getStockHistoryMapOrDefault(
          java.lang.String key,
          dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> map =
            internalGetStockHistoryMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
       */

      public dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory getStockHistoryMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> map =
            internalGetStockHistoryMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
       */
      private java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory>
      getMutableStockHistoryMapMap() {
        return internalGetMutableStockHistoryMap();
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (stockDetails_ != null) {
          output.writeMessage(1, getStockDetails());
        }
        for (java.util.Map.Entry<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> entry
             : internalGetStockHistoryMap().entrySet()) {
          StockHistoryMapDefaultEntryHolder.defaultEntry.serializeTo(
              output, 2, entry.getKey(), entry.getValue());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (stockDetails_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getStockDetails());
        }
        for (java.util.Map.Entry<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> entry
             : internalGetStockHistoryMap().entrySet()) {
          size += StockHistoryMapDefaultEntryHolder.defaultEntry.computeMessageSize(
            2, entry.getKey(), entry.getValue());
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse, Builder> implements
          // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse)
          dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponseOrBuilder {
        // Construct using dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
         */
        public boolean hasStockDetails() {
          return instance.hasStockDetails();
        }
        /**
         * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
         */
        public dalalstreet.socketapi.models.StockOuterClass.Stock getStockDetails() {
          return instance.getStockDetails();
        }
        /**
         * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
         */
        public Builder setStockDetails(dalalstreet.socketapi.models.StockOuterClass.Stock value) {
          copyOnWrite();
          instance.setStockDetails(value);
          return this;
          }
        /**
         * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
         */
        public Builder setStockDetails(
            dalalstreet.socketapi.models.StockOuterClass.Stock.Builder builderForValue) {
          copyOnWrite();
          instance.setStockDetails(builderForValue);
          return this;
        }
        /**
         * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
         */
        public Builder mergeStockDetails(dalalstreet.socketapi.models.StockOuterClass.Stock value) {
          copyOnWrite();
          instance.mergeStockDetails(value);
          return this;
        }
        /**
         * <code>optional .dalalstreet.socketapi.models.Stock stock_details = 1;</code>
         */
        public Builder clearStockDetails() {  copyOnWrite();
          instance.clearStockDetails();
          return this;
        }


        public int getStockHistoryMapCount() {
          return instance.getStockHistoryMapMap().size();
        }
        /**
         * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
         */

        public boolean containsStockHistoryMap(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          return instance.getStockHistoryMapMap().containsKey(key);
        }

        public Builder clearStockHistoryMap() {
          copyOnWrite();
          instance.getMutableStockHistoryMapMap().clear();
          return this;
        }
        /**
         * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
         */

        public Builder removeStockHistoryMap(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          copyOnWrite();
          instance.getMutableStockHistoryMapMap().remove(key);
          return this;
        }
        /**
         * Use {@link #getStockHistoryMapMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> getStockHistoryMap() {
          return getStockHistoryMapMap();
        }
        /**
         * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
         */
        public java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> getStockHistoryMapMap() {
          return java.util.Collections.unmodifiableMap(
              instance.getStockHistoryMapMap());
        }
        /**
         * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
         */

        public dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory getStockHistoryMapOrDefault(
            java.lang.String key,
            dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory defaultValue) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> map =
              instance.getStockHistoryMapMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
         */

        public dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory getStockHistoryMapOrThrow(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> map =
              instance.getStockHistoryMapMap();
          if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
          }
          return map.get(key);
        }
        /**
         * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
         */
        public Builder putStockHistoryMap(
            java.lang.String key,
            dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory value) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          if (value == null) { throw new java.lang.NullPointerException(); }
          copyOnWrite();
          instance.getMutableStockHistoryMapMap().put(key, value);
          return this;
        }
        /**
         * <code>map&lt;string, .dalalstreet.socketapi.models.StockHistory&gt; stock_history_map = 2;</code>
         */
        public Builder putAllStockHistoryMap(
            java.util.Map<java.lang.String, dalalstreet.socketapi.models.StockHistoryOuterClass.StockHistory> values) {
          copyOnWrite();
          instance.getMutableStockHistoryMapMap().putAll(values);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse)
      }
      protected final Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            stockHistoryMap_.makeImmutable();
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse other = (dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse) arg1;
            stockDetails_ = visitor.visitMessage(stockDetails_, other.stockDetails_);
            stockHistoryMap_ = visitor.visitMap(
                stockHistoryMap_, other.internalGetStockHistoryMap());
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
              bitField0_ |= other.bitField0_;
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    dalalstreet.socketapi.models.StockOuterClass.Stock.Builder subBuilder = null;
                    if (stockDetails_ != null) {
                      subBuilder = stockDetails_.toBuilder();
                    }
                    stockDetails_ = input.readMessage(dalalstreet.socketapi.models.StockOuterClass.Stock.parser(), extensionRegistry);
                    if (subBuilder != null) {
                      subBuilder.mergeFrom(stockDetails_);
                      stockDetails_ = subBuilder.buildPartial();
                    }

                    break;
                  }
                  case 18: {
                    if (!stockHistoryMap_.isMutable()) {
                      stockHistoryMap_ = stockHistoryMap_.mutableCopy();
                    }
                    StockHistoryMapDefaultEntryHolder.defaultEntry.parseInto(stockHistoryMap_, input, extensionRegistry);  break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse)
      private static final dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new GetCompanyProfileSuccessResponse();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<GetCompanyProfileSuccessResponse> PARSER;

      public static com.google.protobuf.Parser<GetCompanyProfileSuccessResponse> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int responseCase_ = 0;
    private java.lang.Object response_;
    public enum ResponseCase
        implements com.google.protobuf.Internal.EnumLite {
      RESULT(1),
      BAD_REQUEST_ERROR(2),
      INTERNAL_SERVER_ERROR(3),
      RESPONSE_NOT_SET(0);
      private final int value;
      private ResponseCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResponseCase valueOf(int value) {
        return forNumber(value);
      }

      public static ResponseCase forNumber(int value) {
        switch (value) {
          case 1: return RESULT;
          case 2: return BAD_REQUEST_ERROR;
          case 3: return INTERNAL_SERVER_ERROR;
          case 0: return RESPONSE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ResponseCase
    getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    private void clearResponse() {
      responseCase_ = 0;
      response_ = null;
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse result = 1;</code>
     */
    public dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse getResult() {
      if (responseCase_ == 1) {
         return (dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse) response_;
      }
      return dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse result = 1;</code>
     */
    private void setResult(dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse result = 1;</code>
     */
    private void setResult(
        dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse result = 1;</code>
     */
    private void mergeResult(dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse value) {
      if (responseCase_ == 1 &&
          response_ != dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse.newBuilder((dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse result = 1;</code>
     */
    private void clearResult() {
      if (responseCase_ == 1) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int BAD_REQUEST_ERROR_FIELD_NUMBER = 2;
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    public dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError() {
      if (responseCase_ == 2) {
         return (dalalstreet.socketapi.errors.Errors.BadRequestError) response_;
      }
      return dalalstreet.socketapi.errors.Errors.BadRequestError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void setBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void setBadRequestError(
        dalalstreet.socketapi.errors.Errors.BadRequestError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void mergeBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
      if (responseCase_ == 2 &&
          response_ != dalalstreet.socketapi.errors.Errors.BadRequestError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.errors.Errors.BadRequestError.newBuilder((dalalstreet.socketapi.errors.Errors.BadRequestError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void clearBadRequestError() {
      if (responseCase_ == 2) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int INTERNAL_SERVER_ERROR_FIELD_NUMBER = 3;
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    public dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError() {
      if (responseCase_ == 3) {
         return (dalalstreet.socketapi.errors.Errors.InternalServerError) response_;
      }
      return dalalstreet.socketapi.errors.Errors.InternalServerError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void setInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void setInternalServerError(
        dalalstreet.socketapi.errors.Errors.InternalServerError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void mergeInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
      if (responseCase_ == 3 &&
          response_ != dalalstreet.socketapi.errors.Errors.InternalServerError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.errors.Errors.InternalServerError.newBuilder((dalalstreet.socketapi.errors.Errors.InternalServerError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void clearInternalServerError() {
      if (responseCase_ == 3) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseCase_ == 1) {
        output.writeMessage(1, (dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse) response_);
      }
      if (responseCase_ == 2) {
        output.writeMessage(2, (dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
      }
      if (responseCase_ == 3) {
        output.writeMessage(3, (dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (responseCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse) response_);
      }
      if (responseCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
      }
      if (responseCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.GetCompanyProfileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetCompanyProfileResponse)
        dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponseOrBuilder {
      // Construct using dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public ResponseCase
          getResponseCase() {
        return instance.getResponseCase();
      }

      public Builder clearResponse() {
        copyOnWrite();
        instance.clearResponse();
        return this;
      }


      /**
       * <code>optional .dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse result = 1;</code>
       */
      public dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse getResult() {
        return instance.getResult();
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse result = 1;</code>
       */
      public Builder setResult(dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse value) {
        copyOnWrite();
        instance.setResult(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse result = 1;</code>
       */
      public Builder setResult(
          dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setResult(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse result = 1;</code>
       */
      public Builder mergeResult(dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse value) {
        copyOnWrite();
        instance.mergeResult(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse result = 1;</code>
       */
      public Builder clearResult() {
        copyOnWrite();
        instance.clearResult();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError() {
        return instance.getBadRequestError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder setBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
        copyOnWrite();
        instance.setBadRequestError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder setBadRequestError(
          dalalstreet.socketapi.errors.Errors.BadRequestError.Builder builderForValue) {
        copyOnWrite();
        instance.setBadRequestError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder mergeBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
        copyOnWrite();
        instance.mergeBadRequestError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder clearBadRequestError() {
        copyOnWrite();
        instance.clearBadRequestError();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError() {
        return instance.getInternalServerError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder setInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
        copyOnWrite();
        instance.setInternalServerError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder setInternalServerError(
          dalalstreet.socketapi.errors.Errors.InternalServerError.Builder builderForValue) {
        copyOnWrite();
        instance.setInternalServerError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder mergeInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
        copyOnWrite();
        instance.mergeInternalServerError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder clearInternalServerError() {
        copyOnWrite();
        instance.clearInternalServerError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetCompanyProfileResponse)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse other = (dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse) arg1;
          switch (other.getResponseCase()) {
            case RESULT: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 1,
                  response_,
                  other.response_);
              break;
            }
            case BAD_REQUEST_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 2,
                  response_,
                  other.response_);
              break;
            }
            case INTERNAL_SERVER_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 3,
                  response_,
                  other.response_);
              break;
            }
            case RESPONSE_NOT_SET: {
              visitor.visitOneofNotSet(responseCase_ != 0);
              break;
            }
          }
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            if (other.responseCase_ != 0) {
              responseCase_ = other.responseCase_;
            }
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse.Builder subBuilder = null;
                  if (responseCase_ == 1) {
                    subBuilder = ((dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.GetCompanyProfileSuccessResponse) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 1;
                  break;
                }
                case 18: {
                  dalalstreet.socketapi.errors.Errors.BadRequestError.Builder subBuilder = null;
                  if (responseCase_ == 2) {
                    subBuilder = ((dalalstreet.socketapi.errors.Errors.BadRequestError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.errors.Errors.BadRequestError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 2;
                  break;
                }
                case 26: {
                  dalalstreet.socketapi.errors.Errors.InternalServerError.Builder subBuilder = null;
                  if (responseCase_ == 3) {
                    subBuilder = ((dalalstreet.socketapi.errors.Errors.InternalServerError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.errors.Errors.InternalServerError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 3;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetCompanyProfileResponse)
    private static final dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetCompanyProfileResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static dalalstreet.socketapi.actions.GetCompanyProfile.GetCompanyProfileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetCompanyProfileResponse> PARSER;

    public static com.google.protobuf.Parser<GetCompanyProfileResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
