// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetMarketEvents.proto

package dalalstreet.socketapi.actions;

public final class GetMarketEvents {
  private GetMarketEvents() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GetMarketEventsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetMarketEventsRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 last_event_id = 1;</code>
     */
    int getLastEventId();

    /**
     * <code>optional uint32 count = 2;</code>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code dalalstreet.socketapi.actions.GetMarketEventsRequest}
   */
  public  static final class GetMarketEventsRequest extends
      com.google.protobuf.GeneratedMessageLite<
          GetMarketEventsRequest, GetMarketEventsRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetMarketEventsRequest)
      GetMarketEventsRequestOrBuilder {
    private GetMarketEventsRequest() {
    }
    public static final int LAST_EVENT_ID_FIELD_NUMBER = 1;
    private int lastEventId_;
    /**
     * <code>optional uint32 last_event_id = 1;</code>
     */
    public int getLastEventId() {
      return lastEventId_;
    }
    /**
     * <code>optional uint32 last_event_id = 1;</code>
     */
    private void setLastEventId(int value) {
      
      lastEventId_ = value;
    }
    /**
     * <code>optional uint32 last_event_id = 1;</code>
     */
    private void clearLastEventId() {
      
      lastEventId_ = 0;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional uint32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }
    /**
     * <code>optional uint32 count = 2;</code>
     */
    private void setCount(int value) {
      
      count_ = value;
    }
    /**
     * <code>optional uint32 count = 2;</code>
     */
    private void clearCount() {
      
      count_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lastEventId_ != 0) {
        output.writeUInt32(1, lastEventId_);
      }
      if (count_ != 0) {
        output.writeUInt32(2, count_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (lastEventId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, lastEventId_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, count_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.GetMarketEventsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetMarketEventsRequest)
        dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequestOrBuilder {
      // Construct using dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional uint32 last_event_id = 1;</code>
       */
      public int getLastEventId() {
        return instance.getLastEventId();
      }
      /**
       * <code>optional uint32 last_event_id = 1;</code>
       */
      public Builder setLastEventId(int value) {
        copyOnWrite();
        instance.setLastEventId(value);
        return this;
      }
      /**
       * <code>optional uint32 last_event_id = 1;</code>
       */
      public Builder clearLastEventId() {
        copyOnWrite();
        instance.clearLastEventId();
        return this;
      }

      /**
       * <code>optional uint32 count = 2;</code>
       */
      public int getCount() {
        return instance.getCount();
      }
      /**
       * <code>optional uint32 count = 2;</code>
       */
      public Builder setCount(int value) {
        copyOnWrite();
        instance.setCount(value);
        return this;
      }
      /**
       * <code>optional uint32 count = 2;</code>
       */
      public Builder clearCount() {
        copyOnWrite();
        instance.clearCount();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetMarketEventsRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest other = (dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest) arg1;
          lastEventId_ = visitor.visitInt(lastEventId_ != 0, lastEventId_,
              other.lastEventId_ != 0, other.lastEventId_);
          count_ = visitor.visitInt(count_ != 0, count_,
              other.count_ != 0, other.count_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  lastEventId_ = input.readUInt32();
                  break;
                }
                case 16: {

                  count_ = input.readUInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetMarketEventsRequest)
    private static final dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetMarketEventsRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetMarketEventsRequest> PARSER;

    public static com.google.protobuf.Parser<GetMarketEventsRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetMarketEventsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetMarketEventsResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse result = 1;</code>
     */
    dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse getResult();

    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError();

    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError();

    public dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.ResponseCase getResponseCase();
  }
  /**
   * Protobuf type {@code dalalstreet.socketapi.actions.GetMarketEventsResponse}
   */
  public  static final class GetMarketEventsResponse extends
      com.google.protobuf.GeneratedMessageLite<
          GetMarketEventsResponse, GetMarketEventsResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetMarketEventsResponse)
      GetMarketEventsResponseOrBuilder {
    private GetMarketEventsResponse() {
    }
    public interface GetMarketEventsSuccessResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>optional bool more_exists = 1;</code>
       */
      boolean getMoreExists();

      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
       */
      int getMarketEventsCount();
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
       */
      boolean containsMarketEvents(
          int key);
      /**
       * Use {@link #getMarketEventsMap()} instead.
       */
      @java.lang.Deprecated
      java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent>
      getMarketEvents();
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
       */
      java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent>
      getMarketEventsMap();
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
       */

      dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent getMarketEventsOrDefault(
          int key,
          dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent defaultValue);
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
       */

      dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent getMarketEventsOrThrow(
          int key);
    }
    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse}
     */
    public  static final class GetMarketEventsSuccessResponse extends
        com.google.protobuf.GeneratedMessageLite<
            GetMarketEventsSuccessResponse, GetMarketEventsSuccessResponse.Builder> implements
        // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse)
        GetMarketEventsSuccessResponseOrBuilder {
      private GetMarketEventsSuccessResponse() {
      }
      private int bitField0_;
      public static final int MORE_EXISTS_FIELD_NUMBER = 1;
      private boolean moreExists_;
      /**
       * <code>optional bool more_exists = 1;</code>
       */
      public boolean getMoreExists() {
        return moreExists_;
      }
      /**
       * <code>optional bool more_exists = 1;</code>
       */
      private void setMoreExists(boolean value) {
        
        moreExists_ = value;
      }
      /**
       * <code>optional bool more_exists = 1;</code>
       */
      private void clearMoreExists() {
        
        moreExists_ = false;
      }

      public static final int MARKET_EVENTS_FIELD_NUMBER = 2;
      private static final class MarketEventsDefaultEntryHolder {
        static final com.google.protobuf.MapEntryLite<
            java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> defaultEntry =
                com.google.protobuf.MapEntryLite
                .<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent>newDefaultInstance(
                    com.google.protobuf.WireFormat.FieldType.UINT32,
                    0,
                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                    dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent.getDefaultInstance());
      }
      private com.google.protobuf.MapFieldLite<
          java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> marketEvents_ =
              com.google.protobuf.MapFieldLite.emptyMapField();
      private com.google.protobuf.MapFieldLite<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent>
      internalGetMarketEvents() {
        return marketEvents_;
      }
      private com.google.protobuf.MapFieldLite<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent>
      internalGetMutableMarketEvents() {
        if (!marketEvents_.isMutable()) {
          marketEvents_ = marketEvents_.mutableCopy();
        }
        return marketEvents_;
      }

      public int getMarketEventsCount() {
        return internalGetMarketEvents().size();
      }
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
       */

      public boolean containsMarketEvents(
          int key) {
        
        return internalGetMarketEvents().containsKey(key);
      }
      /**
       * Use {@link #getMarketEventsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> getMarketEvents() {
        return getMarketEventsMap();
      }
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
       */

      public java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> getMarketEventsMap() {
        return java.util.Collections.unmodifiableMap(
            internalGetMarketEvents());
      }
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
       */

      public dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent getMarketEventsOrDefault(
          int key,
          dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent defaultValue) {
        
        java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> map =
            internalGetMarketEvents();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
       */

      public dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent getMarketEventsOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> map =
            internalGetMarketEvents();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
       */
      private java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent>
      getMutableMarketEventsMap() {
        return internalGetMutableMarketEvents();
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (moreExists_ != false) {
          output.writeBool(1, moreExists_);
        }
        for (java.util.Map.Entry<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> entry
             : internalGetMarketEvents().entrySet()) {
          MarketEventsDefaultEntryHolder.defaultEntry.serializeTo(
              output, 2, entry.getKey(), entry.getValue());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (moreExists_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(1, moreExists_);
        }
        for (java.util.Map.Entry<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> entry
             : internalGetMarketEvents().entrySet()) {
          size += MarketEventsDefaultEntryHolder.defaultEntry.computeMessageSize(
            2, entry.getKey(), entry.getValue());
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse, Builder> implements
          // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse)
          dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponseOrBuilder {
        // Construct using dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional bool more_exists = 1;</code>
         */
        public boolean getMoreExists() {
          return instance.getMoreExists();
        }
        /**
         * <code>optional bool more_exists = 1;</code>
         */
        public Builder setMoreExists(boolean value) {
          copyOnWrite();
          instance.setMoreExists(value);
          return this;
        }
        /**
         * <code>optional bool more_exists = 1;</code>
         */
        public Builder clearMoreExists() {
          copyOnWrite();
          instance.clearMoreExists();
          return this;
        }


        public int getMarketEventsCount() {
          return instance.getMarketEventsMap().size();
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
         */

        public boolean containsMarketEvents(
            int key) {
          
          return instance.getMarketEventsMap().containsKey(key);
        }

        public Builder clearMarketEvents() {
          copyOnWrite();
          instance.getMutableMarketEventsMap().clear();
          return this;
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
         */

        public Builder removeMarketEvents(
            int key) {
          
          copyOnWrite();
          instance.getMutableMarketEventsMap().remove(key);
          return this;
        }
        /**
         * Use {@link #getMarketEventsMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> getMarketEvents() {
          return getMarketEventsMap();
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
         */
        public java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> getMarketEventsMap() {
          return java.util.Collections.unmodifiableMap(
              instance.getMarketEventsMap());
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
         */

        public dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent getMarketEventsOrDefault(
            int key,
            dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent defaultValue) {
          
          java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> map =
              instance.getMarketEventsMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
         */

        public dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent getMarketEventsOrThrow(
            int key) {
          
          java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> map =
              instance.getMarketEventsMap();
          if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
          }
          return map.get(key);
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
         */
        public Builder putMarketEvents(
            int key,
            dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent value) {
          
          if (value == null) { throw new java.lang.NullPointerException(); }
          copyOnWrite();
          instance.getMutableMarketEventsMap().put(key, value);
          return this;
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.MarketEvent&gt; market_events = 2;</code>
         */
        public Builder putAllMarketEvents(
            java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.MarketEventOuterClass.MarketEvent> values) {
          copyOnWrite();
          instance.getMutableMarketEventsMap().putAll(values);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse)
      }
      protected final Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            marketEvents_.makeImmutable();
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse other = (dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse) arg1;
            moreExists_ = visitor.visitBoolean(moreExists_ != false, moreExists_,
                other.moreExists_ != false, other.moreExists_);
            marketEvents_ = visitor.visitMap(
                marketEvents_, other.internalGetMarketEvents());
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
              bitField0_ |= other.bitField0_;
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 8: {

                    moreExists_ = input.readBool();
                    break;
                  }
                  case 18: {
                    if (!marketEvents_.isMutable()) {
                      marketEvents_ = marketEvents_.mutableCopy();
                    }
                    MarketEventsDefaultEntryHolder.defaultEntry.parseInto(marketEvents_, input, extensionRegistry);  break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse)
      private static final dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new GetMarketEventsSuccessResponse();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<GetMarketEventsSuccessResponse> PARSER;

      public static com.google.protobuf.Parser<GetMarketEventsSuccessResponse> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int responseCase_ = 0;
    private java.lang.Object response_;
    public enum ResponseCase
        implements com.google.protobuf.Internal.EnumLite {
      RESULT(1),
      BAD_REQUEST_ERROR(2),
      INTERNAL_SERVER_ERROR(3),
      RESPONSE_NOT_SET(0);
      private final int value;
      private ResponseCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResponseCase valueOf(int value) {
        return forNumber(value);
      }

      public static ResponseCase forNumber(int value) {
        switch (value) {
          case 1: return RESULT;
          case 2: return BAD_REQUEST_ERROR;
          case 3: return INTERNAL_SERVER_ERROR;
          case 0: return RESPONSE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ResponseCase
    getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    private void clearResponse() {
      responseCase_ = 0;
      response_ = null;
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse result = 1;</code>
     */
    public dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse getResult() {
      if (responseCase_ == 1) {
         return (dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse) response_;
      }
      return dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse result = 1;</code>
     */
    private void setResult(dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse result = 1;</code>
     */
    private void setResult(
        dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse result = 1;</code>
     */
    private void mergeResult(dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse value) {
      if (responseCase_ == 1 &&
          response_ != dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse.newBuilder((dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse result = 1;</code>
     */
    private void clearResult() {
      if (responseCase_ == 1) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int BAD_REQUEST_ERROR_FIELD_NUMBER = 2;
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    public dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError() {
      if (responseCase_ == 2) {
         return (dalalstreet.socketapi.errors.Errors.BadRequestError) response_;
      }
      return dalalstreet.socketapi.errors.Errors.BadRequestError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void setBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void setBadRequestError(
        dalalstreet.socketapi.errors.Errors.BadRequestError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void mergeBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
      if (responseCase_ == 2 &&
          response_ != dalalstreet.socketapi.errors.Errors.BadRequestError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.errors.Errors.BadRequestError.newBuilder((dalalstreet.socketapi.errors.Errors.BadRequestError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void clearBadRequestError() {
      if (responseCase_ == 2) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int INTERNAL_SERVER_ERROR_FIELD_NUMBER = 3;
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    public dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError() {
      if (responseCase_ == 3) {
         return (dalalstreet.socketapi.errors.Errors.InternalServerError) response_;
      }
      return dalalstreet.socketapi.errors.Errors.InternalServerError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void setInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void setInternalServerError(
        dalalstreet.socketapi.errors.Errors.InternalServerError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void mergeInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
      if (responseCase_ == 3 &&
          response_ != dalalstreet.socketapi.errors.Errors.InternalServerError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.errors.Errors.InternalServerError.newBuilder((dalalstreet.socketapi.errors.Errors.InternalServerError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void clearInternalServerError() {
      if (responseCase_ == 3) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseCase_ == 1) {
        output.writeMessage(1, (dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse) response_);
      }
      if (responseCase_ == 2) {
        output.writeMessage(2, (dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
      }
      if (responseCase_ == 3) {
        output.writeMessage(3, (dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (responseCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse) response_);
      }
      if (responseCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
      }
      if (responseCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.GetMarketEventsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetMarketEventsResponse)
        dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponseOrBuilder {
      // Construct using dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public ResponseCase
          getResponseCase() {
        return instance.getResponseCase();
      }

      public Builder clearResponse() {
        copyOnWrite();
        instance.clearResponse();
        return this;
      }


      /**
       * <code>optional .dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse result = 1;</code>
       */
      public dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse getResult() {
        return instance.getResult();
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse result = 1;</code>
       */
      public Builder setResult(dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse value) {
        copyOnWrite();
        instance.setResult(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse result = 1;</code>
       */
      public Builder setResult(
          dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setResult(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse result = 1;</code>
       */
      public Builder mergeResult(dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse value) {
        copyOnWrite();
        instance.mergeResult(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetMarketEventsResponse.GetMarketEventsSuccessResponse result = 1;</code>
       */
      public Builder clearResult() {
        copyOnWrite();
        instance.clearResult();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError() {
        return instance.getBadRequestError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder setBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
        copyOnWrite();
        instance.setBadRequestError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder setBadRequestError(
          dalalstreet.socketapi.errors.Errors.BadRequestError.Builder builderForValue) {
        copyOnWrite();
        instance.setBadRequestError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder mergeBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
        copyOnWrite();
        instance.mergeBadRequestError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder clearBadRequestError() {
        copyOnWrite();
        instance.clearBadRequestError();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError() {
        return instance.getInternalServerError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder setInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
        copyOnWrite();
        instance.setInternalServerError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder setInternalServerError(
          dalalstreet.socketapi.errors.Errors.InternalServerError.Builder builderForValue) {
        copyOnWrite();
        instance.setInternalServerError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder mergeInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
        copyOnWrite();
        instance.mergeInternalServerError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder clearInternalServerError() {
        copyOnWrite();
        instance.clearInternalServerError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetMarketEventsResponse)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse other = (dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse) arg1;
          switch (other.getResponseCase()) {
            case RESULT: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 1,
                  response_,
                  other.response_);
              break;
            }
            case BAD_REQUEST_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 2,
                  response_,
                  other.response_);
              break;
            }
            case INTERNAL_SERVER_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 3,
                  response_,
                  other.response_);
              break;
            }
            case RESPONSE_NOT_SET: {
              visitor.visitOneofNotSet(responseCase_ != 0);
              break;
            }
          }
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            if (other.responseCase_ != 0) {
              responseCase_ = other.responseCase_;
            }
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse.Builder subBuilder = null;
                  if (responseCase_ == 1) {
                    subBuilder = ((dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.GetMarketEventsSuccessResponse) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 1;
                  break;
                }
                case 18: {
                  dalalstreet.socketapi.errors.Errors.BadRequestError.Builder subBuilder = null;
                  if (responseCase_ == 2) {
                    subBuilder = ((dalalstreet.socketapi.errors.Errors.BadRequestError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.errors.Errors.BadRequestError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 2;
                  break;
                }
                case 26: {
                  dalalstreet.socketapi.errors.Errors.InternalServerError.Builder subBuilder = null;
                  if (responseCase_ == 3) {
                    subBuilder = ((dalalstreet.socketapi.errors.Errors.InternalServerError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.errors.Errors.InternalServerError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 3;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetMarketEventsResponse)
    private static final dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetMarketEventsResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static dalalstreet.socketapi.actions.GetMarketEvents.GetMarketEventsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetMarketEventsResponse> PARSER;

    public static com.google.protobuf.Parser<GetMarketEventsResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
