// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetMortgageDetails.proto

package dalalstreet.socketapi.actions;

public final class GetMortgageDetails {
  private GetMortgageDetails() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GetMortgageDetailsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetMortgageDetailsRequest)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * <pre>
   * Yeah. Empty. No parameters required here.
   * </pre>
   *
   * Protobuf type {@code dalalstreet.socketapi.actions.GetMortgageDetailsRequest}
   */
  public  static final class GetMortgageDetailsRequest extends
      com.google.protobuf.GeneratedMessageLite<
          GetMortgageDetailsRequest, GetMortgageDetailsRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetMortgageDetailsRequest)
      GetMortgageDetailsRequestOrBuilder {
    private GetMortgageDetailsRequest() {
    }
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * Yeah. Empty. No parameters required here.
     * </pre>
     *
     * Protobuf type {@code dalalstreet.socketapi.actions.GetMortgageDetailsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetMortgageDetailsRequest)
        dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequestOrBuilder {
      // Construct using dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetMortgageDetailsRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest other = (dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest) arg1;
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetMortgageDetailsRequest)
    private static final dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetMortgageDetailsRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetMortgageDetailsRequest> PARSER;

    public static com.google.protobuf.Parser<GetMortgageDetailsRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetMortgageDetailsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetMortgageDetailsResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse result = 1;</code>
     */
    dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse getResult();

    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError();

    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError();

    public dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.ResponseCase getResponseCase();
  }
  /**
   * Protobuf type {@code dalalstreet.socketapi.actions.GetMortgageDetailsResponse}
   */
  public  static final class GetMortgageDetailsResponse extends
      com.google.protobuf.GeneratedMessageLite<
          GetMortgageDetailsResponse, GetMortgageDetailsResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetMortgageDetailsResponse)
      GetMortgageDetailsResponseOrBuilder {
    private GetMortgageDetailsResponse() {
    }
    public interface GetMortgageDetailsSuccessResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <pre>
       * key: stockid, value: the details about this mortgage
       * </pre>
       *
       * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
       */
      int getMortgageMapCount();
      /**
       * <pre>
       * key: stockid, value: the details about this mortgage
       * </pre>
       *
       * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
       */
      boolean containsMortgageMap(
          int key);
      /**
       * Use {@link #getMortgageMapMap()} instead.
       */
      @java.lang.Deprecated
      java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails>
      getMortgageMap();
      /**
       * <pre>
       * key: stockid, value: the details about this mortgage
       * </pre>
       *
       * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
       */
      java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails>
      getMortgageMapMap();
      /**
       * <pre>
       * key: stockid, value: the details about this mortgage
       * </pre>
       *
       * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
       */

      dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails getMortgageMapOrDefault(
          int key,
          dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails defaultValue);
      /**
       * <pre>
       * key: stockid, value: the details about this mortgage
       * </pre>
       *
       * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
       */

      dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails getMortgageMapOrThrow(
          int key);
    }
    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse}
     */
    public  static final class GetMortgageDetailsSuccessResponse extends
        com.google.protobuf.GeneratedMessageLite<
            GetMortgageDetailsSuccessResponse, GetMortgageDetailsSuccessResponse.Builder> implements
        // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse)
        GetMortgageDetailsSuccessResponseOrBuilder {
      private GetMortgageDetailsSuccessResponse() {
      }
      public interface MortgageDetailsOrBuilder extends
          // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails)
          com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional uint32 stock_id = 1;</code>
         */
        int getStockId();

        /**
         * <code>optional uint32 num_stocks_in_bank = 2;</code>
         */
        int getNumStocksInBank();
      }
      /**
       * Protobuf type {@code dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails}
       */
      public  static final class MortgageDetails extends
          com.google.protobuf.GeneratedMessageLite<
              MortgageDetails, MortgageDetails.Builder> implements
          // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails)
          MortgageDetailsOrBuilder {
        private MortgageDetails() {
        }
        public static final int STOCK_ID_FIELD_NUMBER = 1;
        private int stockId_;
        /**
         * <code>optional uint32 stock_id = 1;</code>
         */
        public int getStockId() {
          return stockId_;
        }
        /**
         * <code>optional uint32 stock_id = 1;</code>
         */
        private void setStockId(int value) {
          
          stockId_ = value;
        }
        /**
         * <code>optional uint32 stock_id = 1;</code>
         */
        private void clearStockId() {
          
          stockId_ = 0;
        }

        public static final int NUM_STOCKS_IN_BANK_FIELD_NUMBER = 2;
        private int numStocksInBank_;
        /**
         * <code>optional uint32 num_stocks_in_bank = 2;</code>
         */
        public int getNumStocksInBank() {
          return numStocksInBank_;
        }
        /**
         * <code>optional uint32 num_stocks_in_bank = 2;</code>
         */
        private void setNumStocksInBank(int value) {
          
          numStocksInBank_ = value;
        }
        /**
         * <code>optional uint32 num_stocks_in_bank = 2;</code>
         */
        private void clearNumStocksInBank() {
          
          numStocksInBank_ = 0;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          if (stockId_ != 0) {
            output.writeUInt32(1, stockId_);
          }
          if (numStocksInBank_ != 0) {
            output.writeUInt32(2, numStocksInBank_);
          }
        }

        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;

          size = 0;
          if (stockId_ != 0) {
            size += com.google.protobuf.CodedOutputStream
              .computeUInt32Size(1, stockId_);
          }
          if (numStocksInBank_ != 0) {
            size += com.google.protobuf.CodedOutputStream
              .computeUInt32Size(2, numStocksInBank_);
          }
          memoizedSerializedSize = size;
          return size;
        }

        public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
        }
        public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data);
        }
        public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
        }
        public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input);
        }
        public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
              DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
          return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails prototype) {
          return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        /**
         * Protobuf type {@code dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
              dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails, Builder> implements
            // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails)
            dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetailsOrBuilder {
          // Construct using dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails.newBuilder()
          private Builder() {
            super(DEFAULT_INSTANCE);
          }


          /**
           * <code>optional uint32 stock_id = 1;</code>
           */
          public int getStockId() {
            return instance.getStockId();
          }
          /**
           * <code>optional uint32 stock_id = 1;</code>
           */
          public Builder setStockId(int value) {
            copyOnWrite();
            instance.setStockId(value);
            return this;
          }
          /**
           * <code>optional uint32 stock_id = 1;</code>
           */
          public Builder clearStockId() {
            copyOnWrite();
            instance.clearStockId();
            return this;
          }

          /**
           * <code>optional uint32 num_stocks_in_bank = 2;</code>
           */
          public int getNumStocksInBank() {
            return instance.getNumStocksInBank();
          }
          /**
           * <code>optional uint32 num_stocks_in_bank = 2;</code>
           */
          public Builder setNumStocksInBank(int value) {
            copyOnWrite();
            instance.setNumStocksInBank(value);
            return this;
          }
          /**
           * <code>optional uint32 num_stocks_in_bank = 2;</code>
           */
          public Builder clearNumStocksInBank() {
            copyOnWrite();
            instance.clearNumStocksInBank();
            return this;
          }

          // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails)
        }
        protected final Object dynamicMethod(
            com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
            Object arg0, Object arg1) {
          switch (method) {
            case NEW_MUTABLE_INSTANCE: {
              return new dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails();
            }
            case IS_INITIALIZED: {
              return DEFAULT_INSTANCE;
            }
            case MAKE_IMMUTABLE: {
              return null;
            }
            case NEW_BUILDER: {
              return new Builder();
            }
            case VISIT: {
              Visitor visitor = (Visitor) arg0;
              dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails other = (dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails) arg1;
              stockId_ = visitor.visitInt(stockId_ != 0, stockId_,
                  other.stockId_ != 0, other.stockId_);
              numStocksInBank_ = visitor.visitInt(numStocksInBank_ != 0, numStocksInBank_,
                  other.numStocksInBank_ != 0, other.numStocksInBank_);
              if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                  .INSTANCE) {
              }
              return this;
            }
            case MERGE_FROM_STREAM: {
              com.google.protobuf.CodedInputStream input =
                  (com.google.protobuf.CodedInputStream) arg0;
              com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                  (com.google.protobuf.ExtensionRegistryLite) arg1;
              try {
                boolean done = false;
                while (!done) {
                  int tag = input.readTag();
                  switch (tag) {
                    case 0:
                      done = true;
                      break;
                    default: {
                      if (!input.skipField(tag)) {
                        done = true;
                      }
                      break;
                    }
                    case 8: {

                      stockId_ = input.readUInt32();
                      break;
                    }
                    case 16: {

                      numStocksInBank_ = input.readUInt32();
                      break;
                    }
                  }
                }
              } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
              } catch (java.io.IOException e) {
                throw new RuntimeException(
                    new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this));
              } finally {
              }
            }
            case GET_DEFAULT_INSTANCE: {
              return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
              if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails.class) {
                  if (PARSER == null) {
                    PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                  }
                }
              }
              return PARSER;
            }
          }
          throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails)
        private static final dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails DEFAULT_INSTANCE;
        static {
          DEFAULT_INSTANCE = new MortgageDetails();
          DEFAULT_INSTANCE.makeImmutable();
        }

        public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails getDefaultInstance() {
          return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<MortgageDetails> PARSER;

        public static com.google.protobuf.Parser<MortgageDetails> parser() {
          return DEFAULT_INSTANCE.getParserForType();
        }
      }

      public static final int MORTGAGE_MAP_FIELD_NUMBER = 1;
      private static final class MortgageMapDefaultEntryHolder {
        static final com.google.protobuf.MapEntryLite<
            java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> defaultEntry =
                com.google.protobuf.MapEntryLite
                .<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails>newDefaultInstance(
                    com.google.protobuf.WireFormat.FieldType.UINT32,
                    0,
                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                    dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails.getDefaultInstance());
      }
      private com.google.protobuf.MapFieldLite<
          java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> mortgageMap_ =
              com.google.protobuf.MapFieldLite.emptyMapField();
      private com.google.protobuf.MapFieldLite<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails>
      internalGetMortgageMap() {
        return mortgageMap_;
      }
      private com.google.protobuf.MapFieldLite<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails>
      internalGetMutableMortgageMap() {
        if (!mortgageMap_.isMutable()) {
          mortgageMap_ = mortgageMap_.mutableCopy();
        }
        return mortgageMap_;
      }

      public int getMortgageMapCount() {
        return internalGetMortgageMap().size();
      }
      /**
       * <pre>
       * key: stockid, value: the details about this mortgage
       * </pre>
       *
       * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
       */

      public boolean containsMortgageMap(
          int key) {
        
        return internalGetMortgageMap().containsKey(key);
      }
      /**
       * Use {@link #getMortgageMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> getMortgageMap() {
        return getMortgageMapMap();
      }
      /**
       * <pre>
       * key: stockid, value: the details about this mortgage
       * </pre>
       *
       * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
       */

      public java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> getMortgageMapMap() {
        return java.util.Collections.unmodifiableMap(
            internalGetMortgageMap());
      }
      /**
       * <pre>
       * key: stockid, value: the details about this mortgage
       * </pre>
       *
       * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
       */

      public dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails getMortgageMapOrDefault(
          int key,
          dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails defaultValue) {
        
        java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> map =
            internalGetMortgageMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * key: stockid, value: the details about this mortgage
       * </pre>
       *
       * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
       */

      public dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails getMortgageMapOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> map =
            internalGetMortgageMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <pre>
       * key: stockid, value: the details about this mortgage
       * </pre>
       *
       * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
       */
      private java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails>
      getMutableMortgageMapMap() {
        return internalGetMutableMortgageMap();
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (java.util.Map.Entry<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> entry
             : internalGetMortgageMap().entrySet()) {
          MortgageMapDefaultEntryHolder.defaultEntry.serializeTo(
              output, 1, entry.getKey(), entry.getValue());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        for (java.util.Map.Entry<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> entry
             : internalGetMortgageMap().entrySet()) {
          size += MortgageMapDefaultEntryHolder.defaultEntry.computeMessageSize(
            1, entry.getKey(), entry.getValue());
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse, Builder> implements
          // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse)
          dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponseOrBuilder {
        // Construct using dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }



        public int getMortgageMapCount() {
          return instance.getMortgageMapMap().size();
        }
        /**
         * <pre>
         * key: stockid, value: the details about this mortgage
         * </pre>
         *
         * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
         */

        public boolean containsMortgageMap(
            int key) {
          
          return instance.getMortgageMapMap().containsKey(key);
        }

        public Builder clearMortgageMap() {
          copyOnWrite();
          instance.getMutableMortgageMapMap().clear();
          return this;
        }
        /**
         * <pre>
         * key: stockid, value: the details about this mortgage
         * </pre>
         *
         * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
         */

        public Builder removeMortgageMap(
            int key) {
          
          copyOnWrite();
          instance.getMutableMortgageMapMap().remove(key);
          return this;
        }
        /**
         * Use {@link #getMortgageMapMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> getMortgageMap() {
          return getMortgageMapMap();
        }
        /**
         * <pre>
         * key: stockid, value: the details about this mortgage
         * </pre>
         *
         * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
         */
        public java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> getMortgageMapMap() {
          return java.util.Collections.unmodifiableMap(
              instance.getMortgageMapMap());
        }
        /**
         * <pre>
         * key: stockid, value: the details about this mortgage
         * </pre>
         *
         * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
         */

        public dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails getMortgageMapOrDefault(
            int key,
            dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails defaultValue) {
          
          java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> map =
              instance.getMortgageMapMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <pre>
         * key: stockid, value: the details about this mortgage
         * </pre>
         *
         * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
         */

        public dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails getMortgageMapOrThrow(
            int key) {
          
          java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> map =
              instance.getMortgageMapMap();
          if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
          }
          return map.get(key);
        }
        /**
         * <pre>
         * key: stockid, value: the details about this mortgage
         * </pre>
         *
         * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
         */
        public Builder putMortgageMap(
            int key,
            dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails value) {
          
          if (value == null) { throw new java.lang.NullPointerException(); }
          copyOnWrite();
          instance.getMutableMortgageMapMap().put(key, value);
          return this;
        }
        /**
         * <pre>
         * key: stockid, value: the details about this mortgage
         * </pre>
         *
         * <code>map&lt;uint32, .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails&gt; mortgage_map = 1;</code>
         */
        public Builder putAllMortgageMap(
            java.util.Map<java.lang.Integer, dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.MortgageDetails> values) {
          copyOnWrite();
          instance.getMutableMortgageMapMap().putAll(values);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse)
      }
      protected final Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            mortgageMap_.makeImmutable();
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse other = (dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse) arg1;
            mortgageMap_ = visitor.visitMap(
                mortgageMap_, other.internalGetMortgageMap());
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    if (!mortgageMap_.isMutable()) {
                      mortgageMap_ = mortgageMap_.mutableCopy();
                    }
                    MortgageMapDefaultEntryHolder.defaultEntry.parseInto(mortgageMap_, input, extensionRegistry);  break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse)
      private static final dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new GetMortgageDetailsSuccessResponse();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<GetMortgageDetailsSuccessResponse> PARSER;

      public static com.google.protobuf.Parser<GetMortgageDetailsSuccessResponse> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int responseCase_ = 0;
    private java.lang.Object response_;
    public enum ResponseCase
        implements com.google.protobuf.Internal.EnumLite {
      RESULT(1),
      BAD_REQUEST_ERROR(2),
      INTERNAL_SERVER_ERROR(3),
      RESPONSE_NOT_SET(0);
      private final int value;
      private ResponseCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResponseCase valueOf(int value) {
        return forNumber(value);
      }

      public static ResponseCase forNumber(int value) {
        switch (value) {
          case 1: return RESULT;
          case 2: return BAD_REQUEST_ERROR;
          case 3: return INTERNAL_SERVER_ERROR;
          case 0: return RESPONSE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ResponseCase
    getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    private void clearResponse() {
      responseCase_ = 0;
      response_ = null;
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse result = 1;</code>
     */
    public dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse getResult() {
      if (responseCase_ == 1) {
         return (dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse) response_;
      }
      return dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse result = 1;</code>
     */
    private void setResult(dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse result = 1;</code>
     */
    private void setResult(
        dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse result = 1;</code>
     */
    private void mergeResult(dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse value) {
      if (responseCase_ == 1 &&
          response_ != dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.newBuilder((dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse result = 1;</code>
     */
    private void clearResult() {
      if (responseCase_ == 1) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int BAD_REQUEST_ERROR_FIELD_NUMBER = 2;
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    public dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError() {
      if (responseCase_ == 2) {
         return (dalalstreet.socketapi.errors.Errors.BadRequestError) response_;
      }
      return dalalstreet.socketapi.errors.Errors.BadRequestError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void setBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void setBadRequestError(
        dalalstreet.socketapi.errors.Errors.BadRequestError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void mergeBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
      if (responseCase_ == 2 &&
          response_ != dalalstreet.socketapi.errors.Errors.BadRequestError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.errors.Errors.BadRequestError.newBuilder((dalalstreet.socketapi.errors.Errors.BadRequestError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void clearBadRequestError() {
      if (responseCase_ == 2) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int INTERNAL_SERVER_ERROR_FIELD_NUMBER = 3;
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    public dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError() {
      if (responseCase_ == 3) {
         return (dalalstreet.socketapi.errors.Errors.InternalServerError) response_;
      }
      return dalalstreet.socketapi.errors.Errors.InternalServerError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void setInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void setInternalServerError(
        dalalstreet.socketapi.errors.Errors.InternalServerError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void mergeInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
      if (responseCase_ == 3 &&
          response_ != dalalstreet.socketapi.errors.Errors.InternalServerError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.errors.Errors.InternalServerError.newBuilder((dalalstreet.socketapi.errors.Errors.InternalServerError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void clearInternalServerError() {
      if (responseCase_ == 3) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseCase_ == 1) {
        output.writeMessage(1, (dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse) response_);
      }
      if (responseCase_ == 2) {
        output.writeMessage(2, (dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
      }
      if (responseCase_ == 3) {
        output.writeMessage(3, (dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (responseCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse) response_);
      }
      if (responseCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
      }
      if (responseCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.GetMortgageDetailsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetMortgageDetailsResponse)
        dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponseOrBuilder {
      // Construct using dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public ResponseCase
          getResponseCase() {
        return instance.getResponseCase();
      }

      public Builder clearResponse() {
        copyOnWrite();
        instance.clearResponse();
        return this;
      }


      /**
       * <code>optional .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse result = 1;</code>
       */
      public dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse getResult() {
        return instance.getResult();
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse result = 1;</code>
       */
      public Builder setResult(dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse value) {
        copyOnWrite();
        instance.setResult(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse result = 1;</code>
       */
      public Builder setResult(
          dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setResult(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse result = 1;</code>
       */
      public Builder mergeResult(dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse value) {
        copyOnWrite();
        instance.mergeResult(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse result = 1;</code>
       */
      public Builder clearResult() {
        copyOnWrite();
        instance.clearResult();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError() {
        return instance.getBadRequestError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder setBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
        copyOnWrite();
        instance.setBadRequestError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder setBadRequestError(
          dalalstreet.socketapi.errors.Errors.BadRequestError.Builder builderForValue) {
        copyOnWrite();
        instance.setBadRequestError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder mergeBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
        copyOnWrite();
        instance.mergeBadRequestError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder clearBadRequestError() {
        copyOnWrite();
        instance.clearBadRequestError();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError() {
        return instance.getInternalServerError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder setInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
        copyOnWrite();
        instance.setInternalServerError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder setInternalServerError(
          dalalstreet.socketapi.errors.Errors.InternalServerError.Builder builderForValue) {
        copyOnWrite();
        instance.setInternalServerError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder mergeInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
        copyOnWrite();
        instance.mergeInternalServerError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder clearInternalServerError() {
        copyOnWrite();
        instance.clearInternalServerError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetMortgageDetailsResponse)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse other = (dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse) arg1;
          switch (other.getResponseCase()) {
            case RESULT: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 1,
                  response_,
                  other.response_);
              break;
            }
            case BAD_REQUEST_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 2,
                  response_,
                  other.response_);
              break;
            }
            case INTERNAL_SERVER_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 3,
                  response_,
                  other.response_);
              break;
            }
            case RESPONSE_NOT_SET: {
              visitor.visitOneofNotSet(responseCase_ != 0);
              break;
            }
          }
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            if (other.responseCase_ != 0) {
              responseCase_ = other.responseCase_;
            }
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.Builder subBuilder = null;
                  if (responseCase_ == 1) {
                    subBuilder = ((dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.GetMortgageDetailsSuccessResponse) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 1;
                  break;
                }
                case 18: {
                  dalalstreet.socketapi.errors.Errors.BadRequestError.Builder subBuilder = null;
                  if (responseCase_ == 2) {
                    subBuilder = ((dalalstreet.socketapi.errors.Errors.BadRequestError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.errors.Errors.BadRequestError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 2;
                  break;
                }
                case 26: {
                  dalalstreet.socketapi.errors.Errors.InternalServerError.Builder subBuilder = null;
                  if (responseCase_ == 3) {
                    subBuilder = ((dalalstreet.socketapi.errors.Errors.InternalServerError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.errors.Errors.InternalServerError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 3;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetMortgageDetailsResponse)
    private static final dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetMortgageDetailsResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static dalalstreet.socketapi.actions.GetMortgageDetails.GetMortgageDetailsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetMortgageDetailsResponse> PARSER;

    public static com.google.protobuf.Parser<GetMortgageDetailsResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
