// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetTransactions.proto

package dalalstreet.socketapi.actions;

public final class GetTransactions {
  private GetTransactions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GetTransactionsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetTransactionsRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 0 for latest transactions
     * </pre>
     *
     * <code>optional uint32 last_transaction_id = 1;</code>
     */
    int getLastTransactionId();

    /**
     * <pre>
     * Set to 0 for getting max transactions allowed.
     * </pre>
     *
     * <code>optional uint32 count = 2;</code>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code dalalstreet.socketapi.actions.GetTransactionsRequest}
   */
  public  static final class GetTransactionsRequest extends
      com.google.protobuf.GeneratedMessageLite<
          GetTransactionsRequest, GetTransactionsRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetTransactionsRequest)
      GetTransactionsRequestOrBuilder {
    private GetTransactionsRequest() {
    }
    public static final int LAST_TRANSACTION_ID_FIELD_NUMBER = 1;
    private int lastTransactionId_;
    /**
     * <pre>
     * 0 for latest transactions
     * </pre>
     *
     * <code>optional uint32 last_transaction_id = 1;</code>
     */
    public int getLastTransactionId() {
      return lastTransactionId_;
    }
    /**
     * <pre>
     * 0 for latest transactions
     * </pre>
     *
     * <code>optional uint32 last_transaction_id = 1;</code>
     */
    private void setLastTransactionId(int value) {
      
      lastTransactionId_ = value;
    }
    /**
     * <pre>
     * 0 for latest transactions
     * </pre>
     *
     * <code>optional uint32 last_transaction_id = 1;</code>
     */
    private void clearLastTransactionId() {
      
      lastTransactionId_ = 0;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <pre>
     * Set to 0 for getting max transactions allowed.
     * </pre>
     *
     * <code>optional uint32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }
    /**
     * <pre>
     * Set to 0 for getting max transactions allowed.
     * </pre>
     *
     * <code>optional uint32 count = 2;</code>
     */
    private void setCount(int value) {
      
      count_ = value;
    }
    /**
     * <pre>
     * Set to 0 for getting max transactions allowed.
     * </pre>
     *
     * <code>optional uint32 count = 2;</code>
     */
    private void clearCount() {
      
      count_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lastTransactionId_ != 0) {
        output.writeUInt32(1, lastTransactionId_);
      }
      if (count_ != 0) {
        output.writeUInt32(2, count_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (lastTransactionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, lastTransactionId_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, count_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.GetTransactionsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetTransactionsRequest)
        dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequestOrBuilder {
      // Construct using dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 0 for latest transactions
       * </pre>
       *
       * <code>optional uint32 last_transaction_id = 1;</code>
       */
      public int getLastTransactionId() {
        return instance.getLastTransactionId();
      }
      /**
       * <pre>
       * 0 for latest transactions
       * </pre>
       *
       * <code>optional uint32 last_transaction_id = 1;</code>
       */
      public Builder setLastTransactionId(int value) {
        copyOnWrite();
        instance.setLastTransactionId(value);
        return this;
      }
      /**
       * <pre>
       * 0 for latest transactions
       * </pre>
       *
       * <code>optional uint32 last_transaction_id = 1;</code>
       */
      public Builder clearLastTransactionId() {
        copyOnWrite();
        instance.clearLastTransactionId();
        return this;
      }

      /**
       * <pre>
       * Set to 0 for getting max transactions allowed.
       * </pre>
       *
       * <code>optional uint32 count = 2;</code>
       */
      public int getCount() {
        return instance.getCount();
      }
      /**
       * <pre>
       * Set to 0 for getting max transactions allowed.
       * </pre>
       *
       * <code>optional uint32 count = 2;</code>
       */
      public Builder setCount(int value) {
        copyOnWrite();
        instance.setCount(value);
        return this;
      }
      /**
       * <pre>
       * Set to 0 for getting max transactions allowed.
       * </pre>
       *
       * <code>optional uint32 count = 2;</code>
       */
      public Builder clearCount() {
        copyOnWrite();
        instance.clearCount();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetTransactionsRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest other = (dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest) arg1;
          lastTransactionId_ = visitor.visitInt(lastTransactionId_ != 0, lastTransactionId_,
              other.lastTransactionId_ != 0, other.lastTransactionId_);
          count_ = visitor.visitInt(count_ != 0, count_,
              other.count_ != 0, other.count_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  lastTransactionId_ = input.readUInt32();
                  break;
                }
                case 16: {

                  count_ = input.readUInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetTransactionsRequest)
    private static final dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetTransactionsRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetTransactionsRequest> PARSER;

    public static com.google.protobuf.Parser<GetTransactionsRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetTransactionsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetTransactionsResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse result = 1;</code>
     */
    dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse getResult();

    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError();

    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError();

    public dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.ResponseCase getResponseCase();
  }
  /**
   * Protobuf type {@code dalalstreet.socketapi.actions.GetTransactionsResponse}
   */
  public  static final class GetTransactionsResponse extends
      com.google.protobuf.GeneratedMessageLite<
          GetTransactionsResponse, GetTransactionsResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetTransactionsResponse)
      GetTransactionsResponseOrBuilder {
    private GetTransactionsResponse() {
    }
    public interface GetTransactionsSuccessResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
       */
      int getTransactionsMapCount();
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
       */
      boolean containsTransactionsMap(
          int key);
      /**
       * Use {@link #getTransactionsMapMap()} instead.
       */
      @java.lang.Deprecated
      java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction>
      getTransactionsMap();
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
       */
      java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction>
      getTransactionsMapMap();
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
       */

      dalalstreet.socketapi.models.TransactionOuterClass.Transaction getTransactionsMapOrDefault(
          int key,
          dalalstreet.socketapi.models.TransactionOuterClass.Transaction defaultValue);
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
       */

      dalalstreet.socketapi.models.TransactionOuterClass.Transaction getTransactionsMapOrThrow(
          int key);

      /**
       * <code>optional bool more_exists = 2;</code>
       */
      boolean getMoreExists();
    }
    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse}
     */
    public  static final class GetTransactionsSuccessResponse extends
        com.google.protobuf.GeneratedMessageLite<
            GetTransactionsSuccessResponse, GetTransactionsSuccessResponse.Builder> implements
        // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse)
        GetTransactionsSuccessResponseOrBuilder {
      private GetTransactionsSuccessResponse() {
      }
      private int bitField0_;
      public static final int TRANSACTIONS_MAP_FIELD_NUMBER = 1;
      private static final class TransactionsMapDefaultEntryHolder {
        static final com.google.protobuf.MapEntryLite<
            java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> defaultEntry =
                com.google.protobuf.MapEntryLite
                .<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction>newDefaultInstance(
                    com.google.protobuf.WireFormat.FieldType.UINT32,
                    0,
                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                    dalalstreet.socketapi.models.TransactionOuterClass.Transaction.getDefaultInstance());
      }
      private com.google.protobuf.MapFieldLite<
          java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> transactionsMap_ =
              com.google.protobuf.MapFieldLite.emptyMapField();
      private com.google.protobuf.MapFieldLite<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction>
      internalGetTransactionsMap() {
        return transactionsMap_;
      }
      private com.google.protobuf.MapFieldLite<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction>
      internalGetMutableTransactionsMap() {
        if (!transactionsMap_.isMutable()) {
          transactionsMap_ = transactionsMap_.mutableCopy();
        }
        return transactionsMap_;
      }

      public int getTransactionsMapCount() {
        return internalGetTransactionsMap().size();
      }
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
       */

      public boolean containsTransactionsMap(
          int key) {
        
        return internalGetTransactionsMap().containsKey(key);
      }
      /**
       * Use {@link #getTransactionsMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> getTransactionsMap() {
        return getTransactionsMapMap();
      }
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
       */

      public java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> getTransactionsMapMap() {
        return java.util.Collections.unmodifiableMap(
            internalGetTransactionsMap());
      }
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
       */

      public dalalstreet.socketapi.models.TransactionOuterClass.Transaction getTransactionsMapOrDefault(
          int key,
          dalalstreet.socketapi.models.TransactionOuterClass.Transaction defaultValue) {
        
        java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> map =
            internalGetTransactionsMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
       */

      public dalalstreet.socketapi.models.TransactionOuterClass.Transaction getTransactionsMapOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> map =
            internalGetTransactionsMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
       */
      private java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction>
      getMutableTransactionsMapMap() {
        return internalGetMutableTransactionsMap();
      }

      public static final int MORE_EXISTS_FIELD_NUMBER = 2;
      private boolean moreExists_;
      /**
       * <code>optional bool more_exists = 2;</code>
       */
      public boolean getMoreExists() {
        return moreExists_;
      }
      /**
       * <code>optional bool more_exists = 2;</code>
       */
      private void setMoreExists(boolean value) {
        
        moreExists_ = value;
      }
      /**
       * <code>optional bool more_exists = 2;</code>
       */
      private void clearMoreExists() {
        
        moreExists_ = false;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (java.util.Map.Entry<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> entry
             : internalGetTransactionsMap().entrySet()) {
          TransactionsMapDefaultEntryHolder.defaultEntry.serializeTo(
              output, 1, entry.getKey(), entry.getValue());
        }
        if (moreExists_ != false) {
          output.writeBool(2, moreExists_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        for (java.util.Map.Entry<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> entry
             : internalGetTransactionsMap().entrySet()) {
          size += TransactionsMapDefaultEntryHolder.defaultEntry.computeMessageSize(
            1, entry.getKey(), entry.getValue());
        }
        if (moreExists_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(2, moreExists_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse, Builder> implements
          // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse)
          dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponseOrBuilder {
        // Construct using dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }



        public int getTransactionsMapCount() {
          return instance.getTransactionsMapMap().size();
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
         */

        public boolean containsTransactionsMap(
            int key) {
          
          return instance.getTransactionsMapMap().containsKey(key);
        }

        public Builder clearTransactionsMap() {
          copyOnWrite();
          instance.getMutableTransactionsMapMap().clear();
          return this;
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
         */

        public Builder removeTransactionsMap(
            int key) {
          
          copyOnWrite();
          instance.getMutableTransactionsMapMap().remove(key);
          return this;
        }
        /**
         * Use {@link #getTransactionsMapMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> getTransactionsMap() {
          return getTransactionsMapMap();
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
         */
        public java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> getTransactionsMapMap() {
          return java.util.Collections.unmodifiableMap(
              instance.getTransactionsMapMap());
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
         */

        public dalalstreet.socketapi.models.TransactionOuterClass.Transaction getTransactionsMapOrDefault(
            int key,
            dalalstreet.socketapi.models.TransactionOuterClass.Transaction defaultValue) {
          
          java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> map =
              instance.getTransactionsMapMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
         */

        public dalalstreet.socketapi.models.TransactionOuterClass.Transaction getTransactionsMapOrThrow(
            int key) {
          
          java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> map =
              instance.getTransactionsMapMap();
          if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
          }
          return map.get(key);
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
         */
        public Builder putTransactionsMap(
            int key,
            dalalstreet.socketapi.models.TransactionOuterClass.Transaction value) {
          
          if (value == null) { throw new java.lang.NullPointerException(); }
          copyOnWrite();
          instance.getMutableTransactionsMapMap().put(key, value);
          return this;
        }
        /**
         * <code>map&lt;uint32, .dalalstreet.socketapi.models.Transaction&gt; transactions_map = 1;</code>
         */
        public Builder putAllTransactionsMap(
            java.util.Map<java.lang.Integer, dalalstreet.socketapi.models.TransactionOuterClass.Transaction> values) {
          copyOnWrite();
          instance.getMutableTransactionsMapMap().putAll(values);
          return this;
        }

        /**
         * <code>optional bool more_exists = 2;</code>
         */
        public boolean getMoreExists() {
          return instance.getMoreExists();
        }
        /**
         * <code>optional bool more_exists = 2;</code>
         */
        public Builder setMoreExists(boolean value) {
          copyOnWrite();
          instance.setMoreExists(value);
          return this;
        }
        /**
         * <code>optional bool more_exists = 2;</code>
         */
        public Builder clearMoreExists() {
          copyOnWrite();
          instance.clearMoreExists();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse)
      }
      protected final Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            transactionsMap_.makeImmutable();
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse other = (dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse) arg1;
            transactionsMap_ = visitor.visitMap(
                transactionsMap_, other.internalGetTransactionsMap());
            moreExists_ = visitor.visitBoolean(moreExists_ != false, moreExists_,
                other.moreExists_ != false, other.moreExists_);
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
              bitField0_ |= other.bitField0_;
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    if (!transactionsMap_.isMutable()) {
                      transactionsMap_ = transactionsMap_.mutableCopy();
                    }
                    TransactionsMapDefaultEntryHolder.defaultEntry.parseInto(transactionsMap_, input, extensionRegistry);  break;
                  }
                  case 16: {

                    moreExists_ = input.readBool();
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse)
      private static final dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new GetTransactionsSuccessResponse();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<GetTransactionsSuccessResponse> PARSER;

      public static com.google.protobuf.Parser<GetTransactionsSuccessResponse> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int responseCase_ = 0;
    private java.lang.Object response_;
    public enum ResponseCase
        implements com.google.protobuf.Internal.EnumLite {
      RESULT(1),
      BAD_REQUEST_ERROR(2),
      INTERNAL_SERVER_ERROR(3),
      RESPONSE_NOT_SET(0);
      private final int value;
      private ResponseCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResponseCase valueOf(int value) {
        return forNumber(value);
      }

      public static ResponseCase forNumber(int value) {
        switch (value) {
          case 1: return RESULT;
          case 2: return BAD_REQUEST_ERROR;
          case 3: return INTERNAL_SERVER_ERROR;
          case 0: return RESPONSE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ResponseCase
    getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    private void clearResponse() {
      responseCase_ = 0;
      response_ = null;
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse result = 1;</code>
     */
    public dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse getResult() {
      if (responseCase_ == 1) {
         return (dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse) response_;
      }
      return dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse result = 1;</code>
     */
    private void setResult(dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse result = 1;</code>
     */
    private void setResult(
        dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse result = 1;</code>
     */
    private void mergeResult(dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse value) {
      if (responseCase_ == 1 &&
          response_ != dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse.newBuilder((dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse result = 1;</code>
     */
    private void clearResult() {
      if (responseCase_ == 1) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int BAD_REQUEST_ERROR_FIELD_NUMBER = 2;
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    public dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError() {
      if (responseCase_ == 2) {
         return (dalalstreet.socketapi.errors.Errors.BadRequestError) response_;
      }
      return dalalstreet.socketapi.errors.Errors.BadRequestError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void setBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void setBadRequestError(
        dalalstreet.socketapi.errors.Errors.BadRequestError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void mergeBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
      if (responseCase_ == 2 &&
          response_ != dalalstreet.socketapi.errors.Errors.BadRequestError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.errors.Errors.BadRequestError.newBuilder((dalalstreet.socketapi.errors.Errors.BadRequestError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
     */
    private void clearBadRequestError() {
      if (responseCase_ == 2) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int INTERNAL_SERVER_ERROR_FIELD_NUMBER = 3;
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    public dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError() {
      if (responseCase_ == 3) {
         return (dalalstreet.socketapi.errors.Errors.InternalServerError) response_;
      }
      return dalalstreet.socketapi.errors.Errors.InternalServerError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void setInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void setInternalServerError(
        dalalstreet.socketapi.errors.Errors.InternalServerError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void mergeInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
      if (responseCase_ == 3 &&
          response_ != dalalstreet.socketapi.errors.Errors.InternalServerError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.errors.Errors.InternalServerError.newBuilder((dalalstreet.socketapi.errors.Errors.InternalServerError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
     */
    private void clearInternalServerError() {
      if (responseCase_ == 3) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseCase_ == 1) {
        output.writeMessage(1, (dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse) response_);
      }
      if (responseCase_ == 2) {
        output.writeMessage(2, (dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
      }
      if (responseCase_ == 3) {
        output.writeMessage(3, (dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (responseCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse) response_);
      }
      if (responseCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
      }
      if (responseCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.GetTransactionsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.GetTransactionsResponse)
        dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponseOrBuilder {
      // Construct using dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public ResponseCase
          getResponseCase() {
        return instance.getResponseCase();
      }

      public Builder clearResponse() {
        copyOnWrite();
        instance.clearResponse();
        return this;
      }


      /**
       * <code>optional .dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse result = 1;</code>
       */
      public dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse getResult() {
        return instance.getResult();
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse result = 1;</code>
       */
      public Builder setResult(dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse value) {
        copyOnWrite();
        instance.setResult(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse result = 1;</code>
       */
      public Builder setResult(
          dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setResult(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse result = 1;</code>
       */
      public Builder mergeResult(dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse value) {
        copyOnWrite();
        instance.mergeResult(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.GetTransactionsResponse.GetTransactionsSuccessResponse result = 1;</code>
       */
      public Builder clearResult() {
        copyOnWrite();
        instance.clearResult();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError() {
        return instance.getBadRequestError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder setBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
        copyOnWrite();
        instance.setBadRequestError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder setBadRequestError(
          dalalstreet.socketapi.errors.Errors.BadRequestError.Builder builderForValue) {
        copyOnWrite();
        instance.setBadRequestError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder mergeBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
        copyOnWrite();
        instance.mergeBadRequestError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 2;</code>
       */
      public Builder clearBadRequestError() {
        copyOnWrite();
        instance.clearBadRequestError();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError() {
        return instance.getInternalServerError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder setInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
        copyOnWrite();
        instance.setInternalServerError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder setInternalServerError(
          dalalstreet.socketapi.errors.Errors.InternalServerError.Builder builderForValue) {
        copyOnWrite();
        instance.setInternalServerError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder mergeInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
        copyOnWrite();
        instance.mergeInternalServerError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 3;</code>
       */
      public Builder clearInternalServerError() {
        copyOnWrite();
        instance.clearInternalServerError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.GetTransactionsResponse)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse other = (dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse) arg1;
          switch (other.getResponseCase()) {
            case RESULT: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 1,
                  response_,
                  other.response_);
              break;
            }
            case BAD_REQUEST_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 2,
                  response_,
                  other.response_);
              break;
            }
            case INTERNAL_SERVER_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 3,
                  response_,
                  other.response_);
              break;
            }
            case RESPONSE_NOT_SET: {
              visitor.visitOneofNotSet(responseCase_ != 0);
              break;
            }
          }
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            if (other.responseCase_ != 0) {
              responseCase_ = other.responseCase_;
            }
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse.Builder subBuilder = null;
                  if (responseCase_ == 1) {
                    subBuilder = ((dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.GetTransactionsSuccessResponse) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 1;
                  break;
                }
                case 18: {
                  dalalstreet.socketapi.errors.Errors.BadRequestError.Builder subBuilder = null;
                  if (responseCase_ == 2) {
                    subBuilder = ((dalalstreet.socketapi.errors.Errors.BadRequestError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.errors.Errors.BadRequestError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 2;
                  break;
                }
                case 26: {
                  dalalstreet.socketapi.errors.Errors.InternalServerError.Builder subBuilder = null;
                  if (responseCase_ == 3) {
                    subBuilder = ((dalalstreet.socketapi.errors.Errors.InternalServerError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.errors.Errors.InternalServerError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 3;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.GetTransactionsResponse)
    private static final dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetTransactionsResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static dalalstreet.socketapi.actions.GetTransactions.GetTransactionsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetTransactionsResponse> PARSER;

    public static com.google.protobuf.Parser<GetTransactionsResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
