// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/PlaceBidOrder.proto

package dalalstreet.socketapi.actions;

public final class PlaceBidOrder {
  private PlaceBidOrder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PlaceBidOrderRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.PlaceBidOrderRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 stock_id = 1;</code>
     */
    int getStockId();

    /**
     * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
     */
    int getOrderTypeValue();
    /**
     * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
     */
    dalalstreet.socketapi.models.OrderTypeOuterClass.OrderType getOrderType();

    /**
     * <code>optional uint32 price = 3;</code>
     */
    int getPrice();

    /**
     * <code>optional uint32 stock_quantity = 4;</code>
     */
    int getStockQuantity();
  }
  /**
   * Protobuf type {@code dalalstreet.socketapi.actions.PlaceBidOrderRequest}
   */
  public  static final class PlaceBidOrderRequest extends
      com.google.protobuf.GeneratedMessageLite<
          PlaceBidOrderRequest, PlaceBidOrderRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.PlaceBidOrderRequest)
      PlaceBidOrderRequestOrBuilder {
    private PlaceBidOrderRequest() {
    }
    public static final int STOCK_ID_FIELD_NUMBER = 1;
    private int stockId_;
    /**
     * <code>optional uint32 stock_id = 1;</code>
     */
    public int getStockId() {
      return stockId_;
    }
    /**
     * <code>optional uint32 stock_id = 1;</code>
     */
    private void setStockId(int value) {
      
      stockId_ = value;
    }
    /**
     * <code>optional uint32 stock_id = 1;</code>
     */
    private void clearStockId() {
      
      stockId_ = 0;
    }

    public static final int ORDER_TYPE_FIELD_NUMBER = 2;
    private int orderType_;
    /**
     * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
     */
    public int getOrderTypeValue() {
      return orderType_;
    }
    /**
     * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
     */
    public dalalstreet.socketapi.models.OrderTypeOuterClass.OrderType getOrderType() {
      dalalstreet.socketapi.models.OrderTypeOuterClass.OrderType result = dalalstreet.socketapi.models.OrderTypeOuterClass.OrderType.forNumber(orderType_);
      return result == null ? dalalstreet.socketapi.models.OrderTypeOuterClass.OrderType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
     */
    private void setOrderTypeValue(int value) {
        orderType_ = value;
    }
    /**
     * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
     */
    private void setOrderType(dalalstreet.socketapi.models.OrderTypeOuterClass.OrderType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      orderType_ = value.getNumber();
    }
    /**
     * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
     */
    private void clearOrderType() {
      
      orderType_ = 0;
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    private int price_;
    /**
     * <code>optional uint32 price = 3;</code>
     */
    public int getPrice() {
      return price_;
    }
    /**
     * <code>optional uint32 price = 3;</code>
     */
    private void setPrice(int value) {
      
      price_ = value;
    }
    /**
     * <code>optional uint32 price = 3;</code>
     */
    private void clearPrice() {
      
      price_ = 0;
    }

    public static final int STOCK_QUANTITY_FIELD_NUMBER = 4;
    private int stockQuantity_;
    /**
     * <code>optional uint32 stock_quantity = 4;</code>
     */
    public int getStockQuantity() {
      return stockQuantity_;
    }
    /**
     * <code>optional uint32 stock_quantity = 4;</code>
     */
    private void setStockQuantity(int value) {
      
      stockQuantity_ = value;
    }
    /**
     * <code>optional uint32 stock_quantity = 4;</code>
     */
    private void clearStockQuantity() {
      
      stockQuantity_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stockId_ != 0) {
        output.writeUInt32(1, stockId_);
      }
      if (orderType_ != dalalstreet.socketapi.models.OrderTypeOuterClass.OrderType.LIMIT.getNumber()) {
        output.writeEnum(2, orderType_);
      }
      if (price_ != 0) {
        output.writeUInt32(3, price_);
      }
      if (stockQuantity_ != 0) {
        output.writeUInt32(4, stockQuantity_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (stockId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, stockId_);
      }
      if (orderType_ != dalalstreet.socketapi.models.OrderTypeOuterClass.OrderType.LIMIT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, orderType_);
      }
      if (price_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, price_);
      }
      if (stockQuantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, stockQuantity_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.PlaceBidOrderRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.PlaceBidOrderRequest)
        dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequestOrBuilder {
      // Construct using dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional uint32 stock_id = 1;</code>
       */
      public int getStockId() {
        return instance.getStockId();
      }
      /**
       * <code>optional uint32 stock_id = 1;</code>
       */
      public Builder setStockId(int value) {
        copyOnWrite();
        instance.setStockId(value);
        return this;
      }
      /**
       * <code>optional uint32 stock_id = 1;</code>
       */
      public Builder clearStockId() {
        copyOnWrite();
        instance.clearStockId();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
       */
      public int getOrderTypeValue() {
        return instance.getOrderTypeValue();
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
       */
      public Builder setOrderTypeValue(int value) {
        copyOnWrite();
        instance.setOrderTypeValue(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
       */
      public dalalstreet.socketapi.models.OrderTypeOuterClass.OrderType getOrderType() {
        return instance.getOrderType();
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
       */
      public Builder setOrderType(dalalstreet.socketapi.models.OrderTypeOuterClass.OrderType value) {
        copyOnWrite();
        instance.setOrderType(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.models.OrderType order_type = 2;</code>
       */
      public Builder clearOrderType() {
        copyOnWrite();
        instance.clearOrderType();
        return this;
      }

      /**
       * <code>optional uint32 price = 3;</code>
       */
      public int getPrice() {
        return instance.getPrice();
      }
      /**
       * <code>optional uint32 price = 3;</code>
       */
      public Builder setPrice(int value) {
        copyOnWrite();
        instance.setPrice(value);
        return this;
      }
      /**
       * <code>optional uint32 price = 3;</code>
       */
      public Builder clearPrice() {
        copyOnWrite();
        instance.clearPrice();
        return this;
      }

      /**
       * <code>optional uint32 stock_quantity = 4;</code>
       */
      public int getStockQuantity() {
        return instance.getStockQuantity();
      }
      /**
       * <code>optional uint32 stock_quantity = 4;</code>
       */
      public Builder setStockQuantity(int value) {
        copyOnWrite();
        instance.setStockQuantity(value);
        return this;
      }
      /**
       * <code>optional uint32 stock_quantity = 4;</code>
       */
      public Builder clearStockQuantity() {
        copyOnWrite();
        instance.clearStockQuantity();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.PlaceBidOrderRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest other = (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest) arg1;
          stockId_ = visitor.visitInt(stockId_ != 0, stockId_,
              other.stockId_ != 0, other.stockId_);
          orderType_ = visitor.visitInt(orderType_ != 0, orderType_,    other.orderType_ != 0, other.orderType_);
          price_ = visitor.visitInt(price_ != 0, price_,
              other.price_ != 0, other.price_);
          stockQuantity_ = visitor.visitInt(stockQuantity_ != 0, stockQuantity_,
              other.stockQuantity_ != 0, other.stockQuantity_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  stockId_ = input.readUInt32();
                  break;
                }
                case 16: {
                  int rawValue = input.readEnum();

                  orderType_ = rawValue;
                  break;
                }
                case 24: {

                  price_ = input.readUInt32();
                  break;
                }
                case 32: {

                  stockQuantity_ = input.readUInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.PlaceBidOrderRequest)
    private static final dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlaceBidOrderRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PlaceBidOrderRequest> PARSER;

    public static com.google.protobuf.Parser<PlaceBidOrderRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PlaceBidOrderResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.PlaceBidOrderResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse result = 1;</code>
     */
    dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse getResult();

    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError bid_limit_exceeded_error = 2;</code>
     */
    dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError getBidLimitExceededError();

    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError not_enough_cash_error = 3;</code>
     */
    dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError getNotEnoughCashError();

    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 4;</code>
     */
    dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError();

    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 5;</code>
     */
    dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError();

    public dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.ResponseCase getResponseCase();
  }
  /**
   * Protobuf type {@code dalalstreet.socketapi.actions.PlaceBidOrderResponse}
   */
  public  static final class PlaceBidOrderResponse extends
      com.google.protobuf.GeneratedMessageLite<
          PlaceBidOrderResponse, PlaceBidOrderResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.PlaceBidOrderResponse)
      PlaceBidOrderResponseOrBuilder {
    private PlaceBidOrderResponse() {
    }
    public interface PlaceBidOrderSuccessResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>optional uint32 bidId = 1;</code>
       */
      int getBidId();
    }
    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse}
     */
    public  static final class PlaceBidOrderSuccessResponse extends
        com.google.protobuf.GeneratedMessageLite<
            PlaceBidOrderSuccessResponse, PlaceBidOrderSuccessResponse.Builder> implements
        // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse)
        PlaceBidOrderSuccessResponseOrBuilder {
      private PlaceBidOrderSuccessResponse() {
      }
      public static final int BIDID_FIELD_NUMBER = 1;
      private int bidId_;
      /**
       * <code>optional uint32 bidId = 1;</code>
       */
      public int getBidId() {
        return bidId_;
      }
      /**
       * <code>optional uint32 bidId = 1;</code>
       */
      private void setBidId(int value) {
        
        bidId_ = value;
      }
      /**
       * <code>optional uint32 bidId = 1;</code>
       */
      private void clearBidId() {
        
        bidId_ = 0;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (bidId_ != 0) {
          output.writeUInt32(1, bidId_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (bidId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, bidId_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse, Builder> implements
          // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse)
          dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponseOrBuilder {
        // Construct using dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional uint32 bidId = 1;</code>
         */
        public int getBidId() {
          return instance.getBidId();
        }
        /**
         * <code>optional uint32 bidId = 1;</code>
         */
        public Builder setBidId(int value) {
          copyOnWrite();
          instance.setBidId(value);
          return this;
        }
        /**
         * <code>optional uint32 bidId = 1;</code>
         */
        public Builder clearBidId() {
          copyOnWrite();
          instance.clearBidId();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse)
      }
      protected final Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse other = (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse) arg1;
            bidId_ = visitor.visitInt(bidId_ != 0, bidId_,
                other.bidId_ != 0, other.bidId_);
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 8: {

                    bidId_ = input.readUInt32();
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse)
      private static final dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new PlaceBidOrderSuccessResponse();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<PlaceBidOrderSuccessResponse> PARSER;

      public static com.google.protobuf.Parser<PlaceBidOrderSuccessResponse> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public interface BidLimitExceededErrorOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>optional string reason = 1;</code>
       */
      java.lang.String getReason();
      /**
       * <code>optional string reason = 1;</code>
       */
      com.google.protobuf.ByteString
          getReasonBytes();
    }
    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError}
     */
    public  static final class BidLimitExceededError extends
        com.google.protobuf.GeneratedMessageLite<
            BidLimitExceededError, BidLimitExceededError.Builder> implements
        // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError)
        BidLimitExceededErrorOrBuilder {
      private BidLimitExceededError() {
        reason_ = "";
      }
      public static final int REASON_FIELD_NUMBER = 1;
      private java.lang.String reason_;
      /**
       * <code>optional string reason = 1;</code>
       */
      public java.lang.String getReason() {
        return reason_;
      }
      /**
       * <code>optional string reason = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(reason_);
      }
      /**
       * <code>optional string reason = 1;</code>
       */
      private void setReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reason_ = value;
      }
      /**
       * <code>optional string reason = 1;</code>
       */
      private void clearReason() {
        
        reason_ = getDefaultInstance().getReason();
      }
      /**
       * <code>optional string reason = 1;</code>
       */
      private void setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reason_ = value.toStringUtf8();
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!reason_.isEmpty()) {
          output.writeString(1, getReason());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!reason_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getReason());
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError, Builder> implements
          // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError)
          dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededErrorOrBuilder {
        // Construct using dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional string reason = 1;</code>
         */
        public java.lang.String getReason() {
          return instance.getReason();
        }
        /**
         * <code>optional string reason = 1;</code>
         */
        public com.google.protobuf.ByteString
            getReasonBytes() {
          return instance.getReasonBytes();
        }
        /**
         * <code>optional string reason = 1;</code>
         */
        public Builder setReason(
            java.lang.String value) {
          copyOnWrite();
          instance.setReason(value);
          return this;
        }
        /**
         * <code>optional string reason = 1;</code>
         */
        public Builder clearReason() {
          copyOnWrite();
          instance.clearReason();
          return this;
        }
        /**
         * <code>optional string reason = 1;</code>
         */
        public Builder setReasonBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setReasonBytes(value);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError)
      }
      protected final Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError other = (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError) arg1;
            reason_ = visitor.visitString(!reason_.isEmpty(), reason_,
                !other.reason_.isEmpty(), other.reason_);
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    String s = input.readStringRequireUtf8();

                    reason_ = s;
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError)
      private static final dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new BidLimitExceededError();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<BidLimitExceededError> PARSER;

      public static com.google.protobuf.Parser<BidLimitExceededError> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public interface NotEnoughCashErrorOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>optional string reason = 1;</code>
       */
      java.lang.String getReason();
      /**
       * <code>optional string reason = 1;</code>
       */
      com.google.protobuf.ByteString
          getReasonBytes();
    }
    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError}
     */
    public  static final class NotEnoughCashError extends
        com.google.protobuf.GeneratedMessageLite<
            NotEnoughCashError, NotEnoughCashError.Builder> implements
        // @@protoc_insertion_point(message_implements:dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError)
        NotEnoughCashErrorOrBuilder {
      private NotEnoughCashError() {
        reason_ = "";
      }
      public static final int REASON_FIELD_NUMBER = 1;
      private java.lang.String reason_;
      /**
       * <code>optional string reason = 1;</code>
       */
      public java.lang.String getReason() {
        return reason_;
      }
      /**
       * <code>optional string reason = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(reason_);
      }
      /**
       * <code>optional string reason = 1;</code>
       */
      private void setReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reason_ = value;
      }
      /**
       * <code>optional string reason = 1;</code>
       */
      private void clearReason() {
        
        reason_ = getDefaultInstance().getReason();
      }
      /**
       * <code>optional string reason = 1;</code>
       */
      private void setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reason_ = value.toStringUtf8();
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!reason_.isEmpty()) {
          output.writeString(1, getReason());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!reason_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getReason());
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError, Builder> implements
          // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError)
          dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashErrorOrBuilder {
        // Construct using dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional string reason = 1;</code>
         */
        public java.lang.String getReason() {
          return instance.getReason();
        }
        /**
         * <code>optional string reason = 1;</code>
         */
        public com.google.protobuf.ByteString
            getReasonBytes() {
          return instance.getReasonBytes();
        }
        /**
         * <code>optional string reason = 1;</code>
         */
        public Builder setReason(
            java.lang.String value) {
          copyOnWrite();
          instance.setReason(value);
          return this;
        }
        /**
         * <code>optional string reason = 1;</code>
         */
        public Builder clearReason() {
          copyOnWrite();
          instance.clearReason();
          return this;
        }
        /**
         * <code>optional string reason = 1;</code>
         */
        public Builder setReasonBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setReasonBytes(value);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError)
      }
      protected final Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError other = (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError) arg1;
            reason_ = visitor.visitString(!reason_.isEmpty(), reason_,
                !other.reason_.isEmpty(), other.reason_);
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    String s = input.readStringRequireUtf8();

                    reason_ = s;
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError)
      private static final dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new NotEnoughCashError();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<NotEnoughCashError> PARSER;

      public static com.google.protobuf.Parser<NotEnoughCashError> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int responseCase_ = 0;
    private java.lang.Object response_;
    public enum ResponseCase
        implements com.google.protobuf.Internal.EnumLite {
      RESULT(1),
      BID_LIMIT_EXCEEDED_ERROR(2),
      NOT_ENOUGH_CASH_ERROR(3),
      BAD_REQUEST_ERROR(4),
      INTERNAL_SERVER_ERROR(5),
      RESPONSE_NOT_SET(0);
      private final int value;
      private ResponseCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResponseCase valueOf(int value) {
        return forNumber(value);
      }

      public static ResponseCase forNumber(int value) {
        switch (value) {
          case 1: return RESULT;
          case 2: return BID_LIMIT_EXCEEDED_ERROR;
          case 3: return NOT_ENOUGH_CASH_ERROR;
          case 4: return BAD_REQUEST_ERROR;
          case 5: return INTERNAL_SERVER_ERROR;
          case 0: return RESPONSE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ResponseCase
    getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    private void clearResponse() {
      responseCase_ = 0;
      response_ = null;
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse result = 1;</code>
     */
    public dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse getResult() {
      if (responseCase_ == 1) {
         return (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse) response_;
      }
      return dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse result = 1;</code>
     */
    private void setResult(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse result = 1;</code>
     */
    private void setResult(
        dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse result = 1;</code>
     */
    private void mergeResult(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse value) {
      if (responseCase_ == 1 &&
          response_ != dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse.newBuilder((dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 1;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse result = 1;</code>
     */
    private void clearResult() {
      if (responseCase_ == 1) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int BID_LIMIT_EXCEEDED_ERROR_FIELD_NUMBER = 2;
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError bid_limit_exceeded_error = 2;</code>
     */
    public dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError getBidLimitExceededError() {
      if (responseCase_ == 2) {
         return (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError) response_;
      }
      return dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError bid_limit_exceeded_error = 2;</code>
     */
    private void setBidLimitExceededError(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError bid_limit_exceeded_error = 2;</code>
     */
    private void setBidLimitExceededError(
        dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError bid_limit_exceeded_error = 2;</code>
     */
    private void mergeBidLimitExceededError(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError value) {
      if (responseCase_ == 2 &&
          response_ != dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError.newBuilder((dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 2;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError bid_limit_exceeded_error = 2;</code>
     */
    private void clearBidLimitExceededError() {
      if (responseCase_ == 2) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int NOT_ENOUGH_CASH_ERROR_FIELD_NUMBER = 3;
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError not_enough_cash_error = 3;</code>
     */
    public dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError getNotEnoughCashError() {
      if (responseCase_ == 3) {
         return (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError) response_;
      }
      return dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError not_enough_cash_error = 3;</code>
     */
    private void setNotEnoughCashError(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError not_enough_cash_error = 3;</code>
     */
    private void setNotEnoughCashError(
        dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError not_enough_cash_error = 3;</code>
     */
    private void mergeNotEnoughCashError(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError value) {
      if (responseCase_ == 3 &&
          response_ != dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError.newBuilder((dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 3;
    }
    /**
     * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError not_enough_cash_error = 3;</code>
     */
    private void clearNotEnoughCashError() {
      if (responseCase_ == 3) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int BAD_REQUEST_ERROR_FIELD_NUMBER = 4;
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 4;</code>
     */
    public dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError() {
      if (responseCase_ == 4) {
         return (dalalstreet.socketapi.errors.Errors.BadRequestError) response_;
      }
      return dalalstreet.socketapi.errors.Errors.BadRequestError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 4;</code>
     */
    private void setBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 4;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 4;</code>
     */
    private void setBadRequestError(
        dalalstreet.socketapi.errors.Errors.BadRequestError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 4;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 4;</code>
     */
    private void mergeBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
      if (responseCase_ == 4 &&
          response_ != dalalstreet.socketapi.errors.Errors.BadRequestError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.errors.Errors.BadRequestError.newBuilder((dalalstreet.socketapi.errors.Errors.BadRequestError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 4;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 4;</code>
     */
    private void clearBadRequestError() {
      if (responseCase_ == 4) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public static final int INTERNAL_SERVER_ERROR_FIELD_NUMBER = 5;
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 5;</code>
     */
    public dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError() {
      if (responseCase_ == 5) {
         return (dalalstreet.socketapi.errors.Errors.InternalServerError) response_;
      }
      return dalalstreet.socketapi.errors.Errors.InternalServerError.getDefaultInstance();
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 5;</code>
     */
    private void setInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
      if (value == null) {
        throw new NullPointerException();
      }
      response_ = value;
      responseCase_ = 5;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 5;</code>
     */
    private void setInternalServerError(
        dalalstreet.socketapi.errors.Errors.InternalServerError.Builder builderForValue) {
      response_ = builderForValue.build();
      responseCase_ = 5;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 5;</code>
     */
    private void mergeInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
      if (responseCase_ == 5 &&
          response_ != dalalstreet.socketapi.errors.Errors.InternalServerError.getDefaultInstance()) {
        response_ = dalalstreet.socketapi.errors.Errors.InternalServerError.newBuilder((dalalstreet.socketapi.errors.Errors.InternalServerError) response_)
            .mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      responseCase_ = 5;
    }
    /**
     * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 5;</code>
     */
    private void clearInternalServerError() {
      if (responseCase_ == 5) {
        responseCase_ = 0;
        response_ = null;
      }
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseCase_ == 1) {
        output.writeMessage(1, (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse) response_);
      }
      if (responseCase_ == 2) {
        output.writeMessage(2, (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError) response_);
      }
      if (responseCase_ == 3) {
        output.writeMessage(3, (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError) response_);
      }
      if (responseCase_ == 4) {
        output.writeMessage(4, (dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
      }
      if (responseCase_ == 5) {
        output.writeMessage(5, (dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (responseCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse) response_);
      }
      if (responseCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError) response_);
      }
      if (responseCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError) response_);
      }
      if (responseCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
      }
      if (responseCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code dalalstreet.socketapi.actions.PlaceBidOrderResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:dalalstreet.socketapi.actions.PlaceBidOrderResponse)
        dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponseOrBuilder {
      // Construct using dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public ResponseCase
          getResponseCase() {
        return instance.getResponseCase();
      }

      public Builder clearResponse() {
        copyOnWrite();
        instance.clearResponse();
        return this;
      }


      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse result = 1;</code>
       */
      public dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse getResult() {
        return instance.getResult();
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse result = 1;</code>
       */
      public Builder setResult(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse value) {
        copyOnWrite();
        instance.setResult(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse result = 1;</code>
       */
      public Builder setResult(
          dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setResult(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse result = 1;</code>
       */
      public Builder mergeResult(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse value) {
        copyOnWrite();
        instance.mergeResult(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse result = 1;</code>
       */
      public Builder clearResult() {
        copyOnWrite();
        instance.clearResult();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError bid_limit_exceeded_error = 2;</code>
       */
      public dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError getBidLimitExceededError() {
        return instance.getBidLimitExceededError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError bid_limit_exceeded_error = 2;</code>
       */
      public Builder setBidLimitExceededError(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError value) {
        copyOnWrite();
        instance.setBidLimitExceededError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError bid_limit_exceeded_error = 2;</code>
       */
      public Builder setBidLimitExceededError(
          dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError.Builder builderForValue) {
        copyOnWrite();
        instance.setBidLimitExceededError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError bid_limit_exceeded_error = 2;</code>
       */
      public Builder mergeBidLimitExceededError(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError value) {
        copyOnWrite();
        instance.mergeBidLimitExceededError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.BidLimitExceededError bid_limit_exceeded_error = 2;</code>
       */
      public Builder clearBidLimitExceededError() {
        copyOnWrite();
        instance.clearBidLimitExceededError();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError not_enough_cash_error = 3;</code>
       */
      public dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError getNotEnoughCashError() {
        return instance.getNotEnoughCashError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError not_enough_cash_error = 3;</code>
       */
      public Builder setNotEnoughCashError(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError value) {
        copyOnWrite();
        instance.setNotEnoughCashError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError not_enough_cash_error = 3;</code>
       */
      public Builder setNotEnoughCashError(
          dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError.Builder builderForValue) {
        copyOnWrite();
        instance.setNotEnoughCashError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError not_enough_cash_error = 3;</code>
       */
      public Builder mergeNotEnoughCashError(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError value) {
        copyOnWrite();
        instance.mergeNotEnoughCashError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.actions.PlaceBidOrderResponse.NotEnoughCashError not_enough_cash_error = 3;</code>
       */
      public Builder clearNotEnoughCashError() {
        copyOnWrite();
        instance.clearNotEnoughCashError();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 4;</code>
       */
      public dalalstreet.socketapi.errors.Errors.BadRequestError getBadRequestError() {
        return instance.getBadRequestError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 4;</code>
       */
      public Builder setBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
        copyOnWrite();
        instance.setBadRequestError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 4;</code>
       */
      public Builder setBadRequestError(
          dalalstreet.socketapi.errors.Errors.BadRequestError.Builder builderForValue) {
        copyOnWrite();
        instance.setBadRequestError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 4;</code>
       */
      public Builder mergeBadRequestError(dalalstreet.socketapi.errors.Errors.BadRequestError value) {
        copyOnWrite();
        instance.mergeBadRequestError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.BadRequestError bad_request_error = 4;</code>
       */
      public Builder clearBadRequestError() {
        copyOnWrite();
        instance.clearBadRequestError();
        return this;
      }

      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 5;</code>
       */
      public dalalstreet.socketapi.errors.Errors.InternalServerError getInternalServerError() {
        return instance.getInternalServerError();
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 5;</code>
       */
      public Builder setInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
        copyOnWrite();
        instance.setInternalServerError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 5;</code>
       */
      public Builder setInternalServerError(
          dalalstreet.socketapi.errors.Errors.InternalServerError.Builder builderForValue) {
        copyOnWrite();
        instance.setInternalServerError(builderForValue);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 5;</code>
       */
      public Builder mergeInternalServerError(dalalstreet.socketapi.errors.Errors.InternalServerError value) {
        copyOnWrite();
        instance.mergeInternalServerError(value);
        return this;
      }
      /**
       * <code>optional .dalalstreet.socketapi.errors.InternalServerError internal_server_error = 5;</code>
       */
      public Builder clearInternalServerError() {
        copyOnWrite();
        instance.clearInternalServerError();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dalalstreet.socketapi.actions.PlaceBidOrderResponse)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse other = (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse) arg1;
          switch (other.getResponseCase()) {
            case RESULT: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 1,
                  response_,
                  other.response_);
              break;
            }
            case BID_LIMIT_EXCEEDED_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 2,
                  response_,
                  other.response_);
              break;
            }
            case NOT_ENOUGH_CASH_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 3,
                  response_,
                  other.response_);
              break;
            }
            case BAD_REQUEST_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 4,
                  response_,
                  other.response_);
              break;
            }
            case INTERNAL_SERVER_ERROR: {
              response_ = visitor.visitOneofMessage(
                  responseCase_ == 5,
                  response_,
                  other.response_);
              break;
            }
            case RESPONSE_NOT_SET: {
              visitor.visitOneofNotSet(responseCase_ != 0);
              break;
            }
          }
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            if (other.responseCase_ != 0) {
              responseCase_ = other.responseCase_;
            }
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse.Builder subBuilder = null;
                  if (responseCase_ == 1) {
                    subBuilder = ((dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.PlaceBidOrderSuccessResponse) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 1;
                  break;
                }
                case 18: {
                  dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError.Builder subBuilder = null;
                  if (responseCase_ == 2) {
                    subBuilder = ((dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.BidLimitExceededError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 2;
                  break;
                }
                case 26: {
                  dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError.Builder subBuilder = null;
                  if (responseCase_ == 3) {
                    subBuilder = ((dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.NotEnoughCashError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 3;
                  break;
                }
                case 34: {
                  dalalstreet.socketapi.errors.Errors.BadRequestError.Builder subBuilder = null;
                  if (responseCase_ == 4) {
                    subBuilder = ((dalalstreet.socketapi.errors.Errors.BadRequestError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.errors.Errors.BadRequestError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.errors.Errors.BadRequestError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 4;
                  break;
                }
                case 42: {
                  dalalstreet.socketapi.errors.Errors.InternalServerError.Builder subBuilder = null;
                  if (responseCase_ == 5) {
                    subBuilder = ((dalalstreet.socketapi.errors.Errors.InternalServerError) response_).toBuilder();
                  }
                  response_ =
                       input.readMessage(dalalstreet.socketapi.errors.Errors.InternalServerError.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom((dalalstreet.socketapi.errors.Errors.InternalServerError) response_);
                    response_ = subBuilder.buildPartial();
                  }
                  responseCase_ = 5;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:dalalstreet.socketapi.actions.PlaceBidOrderResponse)
    private static final dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlaceBidOrderResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static dalalstreet.socketapi.actions.PlaceBidOrder.PlaceBidOrderResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PlaceBidOrderResponse> PARSER;

    public static com.google.protobuf.Parser<PlaceBidOrderResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
